import { SourceKey } from "./sources";

export interface FightResult {
  weightClass: string;
  fighterA: string;
  fighterB: string;
  winner: string | null; // null の場合は引き分け・中止など
  method: string;
  round?: string;
}

export interface EventResult {
  slug: string;
  org: SourceKey;
  eventName: string;
  date: string; // YYYY-MM-DD
  venue?: string;
  sourceUrl?: string;
  fights: FightResult[];
}

export const EVENT_RESULTS: EventResult[] = [
  {
    slug: "pancrase-363",
    org: "pancrase",
    eventName: "PANCRASE 363",
    date: "2026-06-28",
    venue: "東京・ニューピアホール",
    sourceUrl: "https://www.pancrase.co.jp/data/result/2026/0628.html",
    fights: [
      {
        weightClass: "フェザー級暫定王座決定戦",
        fighterA: "オタベク・ラジャボフ",
        fighterB: "木下尚祐",
        winner: "オタベク・ラジャボフ",
        method: "三角絞め",
        round: "3R 2:45",
      },
      {
        weightClass: "ライト級",
        fighterA: "粕谷優介",
        fighterB: "神谷大智",
        winner: "神谷大智",
        method: "TKO（グラウンドパンチ）",
        round: "2R 3:39",
      },
      {
        weightClass: "フライ級",
        fighterA: "谷村泰嘉",
        fighterB: "眞藤源太",
        winner: "眞藤源太",
        method: "ニンジャチョーク",
        round: "3R 4:25",
      },
      {
        weightClass: "ストロー級",
        fighterA: "氏原快聖",
        fighterB: "寺岡拓永",
        winner: null,
        method: "判定（0-0）— ドロー",
        round: "3R 5:00",
      },
      {
        weightClass: "フェザー級",
        fighterA: "亀井晨佑",
        fighterB: "畠山佑介",
        winner: "畠山佑介",
        method: "TKO（グラウンドパンチ）",
        round: "3R 3:50",
      },
      {
        weightClass: "ウェルター級",
        fighterA: "武者光太郎",
        fighterB: "萱沼哲平",
        winner: "武者光太郎",
        method: "TKO（グラウンドパンチ）",
        round: "2R 2:50",
      },
      {
        weightClass: "ライト級",
        fighterA: "下山楓人",
        fighterB: "宮本樹",
        winner: "宮本樹",
        method: "TKO（グラウンドパンチ）",
        round: "2R 4:13",
      },
      {
        weightClass: "バンタム級",
        fighterA: "筑紫淳平",
        fighterB: "鈴木優太郎",
        winner: "筑紫淳平",
        method: "裸絞め",
        round: "1R 1:12",
      },
      {
        weightClass: "バンタム級",
        fighterA: "増田蓮央",
        fighterB: "村社大河",
        winner: "増田蓮央",
        method: "フロントチョーク",
        round: "1R 2:36",
      },
      {
        weightClass: "バンタム級",
        fighterA: "抜井祥輝",
        fighterB: "近藤優馬",
        winner: "近藤優馬",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "小野智也",
        fighterB: "前川慧",
        winner: null,
        method: "試合中止（前川 計量失格）",
      },
    ],
  },
  {
    slug: "shooto-torao-2026",
    org: "shooto",
    eventName: "Lemino修斗TORAO",
    date: "2026-06-28",
    venue: "福岡・アクロス福岡イベントホール",
    sourceUrl: "https://j-shooto.com/2026/06/28/post-50832/",
    fights: [
      {
        weightClass: "フェザー級（-65.8kg）",
        fighterA: "TOMA",
        fighterB: "田中半蔵",
        winner: "TOMA",
        method: "TKO",
        round: "2R 1:09",
      },
      {
        weightClass: "バンタム級（61.2kg）",
        fighterA: "野瀬翔平",
        fighterB: "青柳洸志",
        winner: "野瀬翔平",
        method: "肩固め",
        round: "1R 3:19",
      },
      {
        weightClass: "フライ級（-56.7kg）",
        fighterA: "上田将年",
        fighterB: "打威致",
        winner: "打威致",
        method: "TKO",
        round: "1R 3:51",
      },
      {
        weightClass: "フェザー級（-65.8kg）",
        fighterA: "ナイン・ダイネッシュ",
        fighterB: "久保村佳照",
        winner: "ナイン・ダイネッシュ",
        method: "TKO",
        round: "1R 1:13",
      },
      {
        weightClass: "ストロー級（52.2kg）",
        fighterA: "緑真作",
        fighterB: "梅木勇徳",
        winner: "梅木勇徳",
        method: "判定（0-3）",
      },
      {
        weightClass: "フェザー級（-65.8kg）",
        fighterA: "本松要",
        fighterB: "柿原翔太",
        winner: "柿原翔太",
        method: "KO",
        round: "2R 2:08",
      },
      {
        weightClass: "フェザー級（-65.8kg）",
        fighterA: "山田龍馬",
        fighterB: "深町巧",
        winner: "深町巧",
        method: "裸絞め",
        round: "2R 2:02",
      },
      {
        weightClass: "フライ級（-56.7kg）",
        fighterA: "高宮稜",
        fighterB: "竹本葵天",
        winner: null,
        method: "判定（1-0）— ドロー",
      },
      {
        weightClass: "ストロー級（52.2kg）",
        fighterA: "新誠",
        fighterB: "佐野光輝",
        winner: "佐野光輝",
        method: "三角絞め",
        round: "1R 2:19",
      },
      {
        weightClass: "ストロー級（52.2kg）",
        fighterA: "和氣輝央",
        fighterB: "高井裕翔",
        winner: "高井裕翔",
        method: "KO",
        round: "1R 0:28",
      },
    ],
  },
  {
    slug: "pancrase-362",
    org: "pancrase",
    eventName: "PANCRASE 362",
    date: "2026-05-31",
    venue: "東京・立川ステージガーデン",
    sourceUrl: "https://www.pancrase.co.jp/data/result/2026/0531.html",
    fights: [
      {
        weightClass: "King of Pancraseフライ級王座決定戦",
        fighterA: "時田隆成",
        fighterB: "岸田宙大",
        winner: "時田隆成",
        method: "判定（2-1）",
        round: "5R 5:00",
      },
      {
        weightClass: "バンタム級暫定王座決定戦",
        fighterA: "宮城成歩滝",
        fighterB: "山口怜臣",
        winner: "宮城成歩滝",
        method: "判定（0-3）",
        round: "5R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "濱田巧",
        fighterB: "ジョセフ・カマチョ",
        winner: "濱田巧",
        method: "フロントチョーク",
        round: "2R 1:05",
      },
      {
        weightClass: "フェザー級",
        fighterA: "三宅輝砂",
        fighterB: "遠藤来生",
        winner: "三宅輝砂",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "ライト級",
        fighterA: "鈴木慈也",
        fighterB: "平信一",
        winner: "鈴木慈也",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "バンタム級",
        fighterA: "バラカトゥロ・アサドゥラエフ",
        fighterB: "矢澤諒",
        winner: "バラカトゥロ・アサドゥラエフ",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "キャッチウェイト",
        fighterA: "時田一生",
        fighterB: "藤野武",
        winner: "時田一生",
        method: "裸絞め",
        round: "1R 2:17",
      },
      {
        weightClass: "フェザー級",
        fighterA: "福里凱亜",
        fighterB: "沢木純也",
        winner: "福里凱亜",
        method: "判定（3-0）",
        round: "3R 5:00",
      },
      {
        weightClass: "バンタム級",
        fighterA: "平澤宏樹",
        fighterB: "髙木徳三",
        winner: "平澤宏樹",
        method: "ツイスター",
        round: "2R 1:30",
      },
      {
        weightClass: "バンタム級",
        fighterA: "谷村泰和",
        fighterB: "水島和磨",
        winner: "谷村泰和",
        method: "判定（2-1）",
        round: "3R 5:00",
      },
      {
        weightClass: "バンタム級",
        fighterA: "石原健流",
        fighterB: "小山敬司",
        winner: "石原健流",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "齋藤楼貴",
        fighterB: "嶺大基",
        winner: "齋藤楼貴",
        method: "判定（2-1）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "天坂匡孝",
        fighterB: "稲垣祐司",
        winner: "天坂匡孝",
        method: "肩固め",
        round: "2R 2:07",
      },
      {
        weightClass: "フライ級",
        fighterA: "獅道",
        fighterB: "佐々木裕亮",
        winner: "獅道",
        method: "腕ひしぎ十字固め",
        round: "1R 1:44",
      },
    ],
  },
  {
    slug: "pancrase-361",
    org: "pancrase",
    eventName: "PANCRASE 361",
    date: "2026-03-14",
    venue: "神奈川・横浜武道館",
    sourceUrl: "https://www.pancrase.co.jp/data/result/2026/0314.html",
    fights: [
      {
        weightClass: "ライト級王座決定戦",
        fighterA: "雑賀ヤン坊達也",
        fighterB: "ラファエル・バルボーザ",
        winner: "ラファエル・バルボーザ",
        method: "TKO（目元の負傷）",
        round: "2R 4:41",
      },
      {
        weightClass: "女子フライ級王座決定戦",
        fighterA: "杉山しずか",
        fighterB: "和田綾音",
        winner: "杉山しずか",
        method: "判定（3-0）",
        round: "5R 5:00",
      },
      {
        weightClass: "ストロー級王座決定戦",
        fighterA: "船田電池",
        fighterB: "宮澤雄大",
        winner: "宮澤雄大",
        method: "判定（1-2）",
        round: "5R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "伊藤盛一郎",
        fighterB: "ジョセフ・カマチョ",
        winner: null,
        method: "ノーコンテスト",
      },
      {
        weightClass: "フライ級",
        fighterA: "大塚智貴",
        fighterB: "猿飛流",
        winner: "猿飛流",
        method: "TKO（グラウンドパンチ）",
        round: "2R 0:25",
      },
      {
        weightClass: "ウェルター級",
        fighterA: "内藤由良",
        fighterB: "ガブリエル・レヴェン",
        winner: "内藤由良",
        method: "判定（3-0）",
        round: "3R 5:00",
      },
      {
        weightClass: "バンタム級",
        fighterA: "山木麻弥",
        fighterB: "荒田大輝",
        winner: "荒田大輝",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "ライト級",
        fighterA: "神谷大智",
        fighterB: "葛西和希",
        winner: "神谷大智",
        method: "判定（2-1）",
        round: "3R 5:00",
      },
      {
        weightClass: "70kg契約",
        fighterA: "透暉鷹",
        fighterB: "ギリェルメ・ナカガワ",
        winner: "透暉鷹",
        method: "TKO（グラウンドパンチ）",
        round: "1R 4:33",
      },
      {
        weightClass: "フェザー級",
        fighterA: "木下尚祐",
        fighterB: "シン・ジェヨン",
        winner: "木下尚祐",
        method: "判定（3-0）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "岸田宙大",
        fighterB: "眞藤源太",
        winner: "岸田宙大",
        method: "三角絞め",
        round: "1R 2:38",
      },
      {
        weightClass: "フェザー級",
        fighterA: "岡田拓真",
        fighterB: "清水博人",
        winner: "清水博人",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "菅歩夢",
        fighterB: "谷村泰嘉",
        winner: "菅歩夢",
        method: "フロントチョーク",
        round: "1R 1:06",
      },
      {
        weightClass: "ミドル級",
        fighterA: "平田旭",
        fighterB: "林源平",
        winner: "平田旭",
        method: "TKO（立ち技パンチ）",
        round: "1R 3:17",
      },
      {
        weightClass: "ストロー級",
        fighterA: "リトル",
        fighterB: "佐々木瞬真",
        winner: "佐々木瞬真",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
    ],
  },
  {
    slug: "deep-osaka-impact-2026-3rd-round",
    org: "deep",
    eventName: "DEEP OSAKA IMPACT 2026 3rd ROUND",
    date: "2026-06-21",
    venue: "錦秀会 住吉区民センター大ホール（大阪）",
    sourceUrl:
      "https://www.deep2001.com/deep%e8%a5%bf%e6%97%a5%e6%9c%ac%e3%83%90%e3%83%b3%e3%82%bf%e3%83%a0%e7%b4%9agp%ef%bc%91%e5%9b%9e%e6%88%a6%e3%80%81%e6%a0%97%e5%b1%b1%e8%91%b5%e3%81%8c%e5%9b%bd%e9%9a%9b%e6%88%a6%e3%81%ab%e6%8c%91/",
    fights: [
      {
        weightClass: "DEEP JEWELSフライ級",
        fighterA: "栗山葵",
        fighterB: "サラ・マームード",
        winner: "サラ・マームード",
        method: "判定（1-2）",
      },
      {
        weightClass: "DEEPライト級",
        fighterA: "Street♡★Bob洸助",
        fighterB: "河坂修斗",
        winner: "Street♡★Bob洸助",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "小川道的",
        fighterB: "澤田龍美",
        winner: "小川道的",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "麦谷悠成",
        fighterB: "杉映都",
        winner: "麦谷悠成",
        method: "裸絞め",
        round: "2R 1:37",
      },
      {
        weightClass: "DEEP 68kg契約",
        fighterA: "田中雄大",
        fighterB: "田中壱季",
        winner: "田中雄大",
        method: "裸絞め",
        round: "1R 4:04",
      },
      {
        weightClass: "DEEPストロー級",
        fighterA: "武蔵",
        fighterB: "小柳泰牙",
        winner: "武蔵",
        method: "裸絞め",
        round: "1R 4:34",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "澄斗",
        fighterB: "秋田良隆",
        winner: "澄斗",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "Fernando",
        fighterB: "カーレッジユウキ",
        winner: "Fernando",
        method: "裸絞め",
        round: "2R 2:43",
      },
      {
        weightClass: "DEEP JEWELSストロー級",
        fighterA: "橋本葵",
        fighterB: "渡辺真央",
        winner: "渡辺真央",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEP JEWELS 50kg契約",
        fighterA: "あー子",
        fighterB: "西口日奈子",
        winner: "西口日奈子",
        method: "判定（1-2）",
      },
      {
        weightClass: "DEEPウェルター級",
        fighterA: "山本怜旺",
        fighterB: "居谷匠真",
        winner: "居谷匠真",
        method: "TKO",
        round: "2R 0:35",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "加藤憂也",
        fighterB: "大島伊玖都",
        winner: "加藤憂也",
        method: "TKO",
        round: "1R 2:54",
      },
      {
        weightClass: "DEEP西日本バンタム級GP 1回戦",
        fighterA: "前薗渓",
        fighterB: "木下竜馬",
        winner: "前薗渓",
        method: "裸絞め",
        round: "3R 1:35",
      },
      {
        weightClass: "DEEP西日本バンタム級GP 1回戦",
        fighterA: "切嶋龍輝",
        fighterB: "寺崎昇龍",
        winner: "切嶋龍輝",
        method: "TKO",
        round: "2R 5:00",
      },
      {
        weightClass: "DEEP西日本バンタム級GP 1回戦",
        fighterA: "大空斗",
        fighterB: "谷岡祐樹",
        winner: "大空斗",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEP西日本バンタム級GP 1回戦",
        fighterA: "MG眞介",
        fighterB: "みやび",
        winner: "MG眞介",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPメガトン級",
        fighterA: "稲田将",
        fighterB: "西川将輝",
        winner: "稲田将",
        method: "TKO",
        round: "2R 3:31",
      },
      {
        weightClass: "DEEPウェルター級",
        fighterA: "虎鉄",
        fighterB: "窪田大羅",
        winner: "虎鉄",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEP JEWELSフライ級",
        fighterA: "鈴木QPまい",
        fighterB: "ルリ・サンシャイン",
        winner: "ルリ・サンシャイン",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "古根川充",
        fighterB: "権藤大剛",
        winner: "古根川充",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEPメガトン級",
        fighterA: "ステファン“スマッシュ”",
        fighterB: "酒井天佑",
        winner: "ステファン“スマッシュ”",
        method: "TKO",
        round: "1R 1:19",
      },
    ],
  },
  {
    slug: "deep-nagoya-impact-2026-2nd-round",
    org: "deep",
    eventName: "DEEP NAGOYA IMPACT 2026 2nd ROUND公武堂ファイト",
    date: "2026-06-14",
    venue: "刈谷市産業振興センター あいおいホール",
    sourceUrl:
      "https://www.deep2001.com/%e3%83%a1%e3%82%a4%e3%83%b3%e3%81%aftatsumi%e3%81%ae%e5%be%a9%e5%b8%b0%e6%88%a6%e3%80%81%e3%80%8edeep-nagoya-impact-2026-2nd-round%e3%80%8f%e3%81%ae%e8%a9%a6%e5%90%88%e7%b5%90%e6%9e%9c/",
    fights: [
      {
        weightClass: "DEEPフェザー級",
        fighterA: "アジョウ海翔",
        fighterB: "TATSUMI",
        winner: "アジョウ海翔",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPウェルター級",
        fighterA: "浅野功",
        fighterB: "カーン・ソグズ",
        winner: "浅野功",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "時任琉空",
        fighterB: "鈴木幹也",
        winner: "時任琉空",
        method: "腕ひしぎ十字固め",
        round: "1R 4:32",
      },
      {
        weightClass: "DEEPストロー級",
        fighterA: "鶴人",
        fighterB: "上村稜真",
        winner: "鶴人",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "ビオレス熊座",
        fighterB: "中川内隼人",
        winner: "ビオレス熊座",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "大澤昊",
        fighterB: "ケヴィン・ギノザ",
        winner: "大澤昊",
        method: "判定（0-3）",
      },
      {
        weightClass: "MAXFC JAPAN -48kg契約",
        fighterA: "ユリカ",
        fighterB: "パク・ソヨン",
        winner: "ユリカ",
        method: "TKO（2R終了時）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "吉田翼",
        fighterB: "SHOYA",
        winner: "吉田翼",
        method: "裸絞め",
        round: "2R 2:38",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "杉村翔馬",
        fighterB: "石田ガリットカツヤ",
        winner: "杉村翔馬",
        method: "判定（0-3）",
      },
      {
        weightClass: "MAXFC JAPAN -54kg契約",
        fighterA: "アカリ",
        fighterB: "チェ・ウンジ",
        winner: "アカリ",
        method: "TKO（延長0:30）",
      },
      {
        weightClass: "DEEPフェザー級（アマチュア）",
        fighterA: "三嶌靖丈",
        fighterB: "青井優馬",
        winner: "三嶌靖丈",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPフライ級（アマチュア）",
        fighterA: "早田大也",
        fighterB: "黒川光司",
        winner: "早田大也",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "三塚祐介",
        fighterB: "永井寛人",
        winner: "三塚祐介",
        method: "腕ひしぎ十字固め",
        round: "1R 3:28",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "橋上颯馬",
        fighterB: "古市陸",
        winner: "橋上颯馬",
        method: "裸絞め",
        round: "1R 2:42",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "椿薫",
        fighterB: "青城翔",
        winner: "椿薫",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "山田優太",
        fighterB: "川端凛人",
        winner: "山田優太",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPバンタム級（アマチュア）",
        fighterA: "内田稜我",
        fighterB: "吉口誠也",
        winner: "内田稜我",
        method: "三角絞め",
        round: "1R 2:45",
      },
      {
        weightClass: "DEEPバンタム級（アマチュア）",
        fighterA: "真下健史",
        fighterB: "土屋太郎",
        winner: "真下健史",
        method: "TKO",
        round: "2R 2:40",
      },
      {
        weightClass: "DEEPバンタム級（アマチュア）",
        fighterA: "倉富律世",
        fighterB: "細川輝樹",
        winner: "倉富律世",
        method: "判定（0-3）",
      },
    ],
  },
  {
    slug: "rizin-52",
    org: "rizin",
    eventName: "RIZIN.52",
    date: "2026-03-07",
    venue: "有明アリーナ",
    sourceUrl: "https://ja.wikipedia.org/wiki/RIZIN.52",
    fights: [
      {
        weightClass: "第1試合 MMAルール 49.0kg契約ワンマッチ 5分3R",
        fighterA: "NOEL",
        fighterB: "イ・ボミ",
        winner: "NOEL",
        method: "1R 2:07 ギロチンチョーク",
      },
      {
        weightClass: "第2試合 MMAルール 57.0kg契約ワンマッチ 5分3R",
        fighterA: "新井丈",
        fighterB: "イ・ジョンヒョン",
        winner: "イ・ジョンヒョン",
        method: "3R 3:44 TKO（左フック）",
      },
      {
        weightClass: "第3試合 MMAルール 57.0kg契約ワンマッチ 5分3R",
        fighterA: "征矢貴",
        fighterB: "トニー・ララミー",
        winner: "トニー・ララミー",
        method: "3R 2:00 TKO（右フック→パウンド）",
      },
      {
        weightClass: "第4試合 MMAルール 61.0kg契約ワンマッチ 5分3R",
        fighterA: "佐藤将光",
        fighterB: "ジョン・スウィーニー",
        winner: "佐藤将光",
        method: "1R 4:49 三角絞め",
      },
      {
        weightClass: "第5試合 MMAルール 71.0kg契約ワンマッチ 5分3R",
        fighterA: "キム・ギョンピョ",
        fighterB: "矢地祐介",
        winner: "キム・ギョンピョ",
        method: "2R 4:25 TKO（ドクターストップ：カットでの出血）",
      },
      {
        weightClass: "第6試合 MMAルール 61.0kg契約ワンマッチ 5分3R",
        fighterA: "所英男",
        fighterB: "鹿志村仁之介",
        winner: "鹿志村仁之介",
        method: "1R 1:06 スピニングチョーク",
      },
      {
        weightClass: "第7試合 MMAルール 59.0kg契約ワンマッチ 5分3R",
        fighterA: "伊藤裕樹",
        fighterB: "カルロス・モタ",
        winner: "伊藤裕樹",
        method: "1R 2:27 TKO（左ストレート→パウンド）",
      },
      {
        weightClass: "第8試合 MMAルール 49.0kg契約ワンマッチ 5分3R",
        fighterA: "大島沙緒里",
        fighterB: "ケイト・ロータス",
        winner: "大島沙緒里",
        method: "3R終了 判定3-0 (29-28、29-28、29-28)",
      },
      {
        weightClass: "第9試合 MMAルール 71.0kg契約ワンマッチ 5分3R",
        fighterA: "ビクター・コレスニック",
        fighterB: "武田光司",
        winner: "武田光司",
        method: "3R終了 判定0-3 (28-29、28-29、28-29)",
      },
      {
        weightClass: "第10試合 MMAルール 66.0kg契約ワンマッチ 5分3R",
        fighterA: "高木凌",
        fighterB: "木村柊也",
        winner: "高木凌",
        method: "1R 5:00 TKO（ドクターストップ：眼の負傷）",
      },
      {
        weightClass: "第11試合 MMAルール 71.0kg契約ワンマッチ 5分3R",
        fighterA: "ルイス・グスタボ",
        fighterB: "桜庭大世",
        winner: "ルイス・グスタボ",
        method: "2R 1:32 KO（右フック）",
      },
      {
        weightClass: "第12試合 MMAルール 66.0kg契約ワンマッチ 5分3R",
        fighterA: "秋元強真",
        fighterB: "パッチー・ミックス",
        winner: "秋元強真",
        method: "2R 0:37 TKO（左ストレート→サッカーボールキック）",
      },
    ],
  },
  {
    slug: "rizin-53",
    org: "rizin",
    eventName: "RIZIN.53",
    date: "2026-05-10",
    venue: "GLION ARENA KOBE",
    sourceUrl: "https://ja.wikipedia.org/wiki/RIZIN.53",
    fights: [
      {
        weightClass: "第1試合 キックボクシングルール 57.0kg契約ワンマッチ 3分3R",
        fighterA: "祥汰",
        fighterB: "須藤智也",
        winner: "祥汰",
        method: "3R終了 判定3-0",
      },
      {
        weightClass: "第2試合 キックボクシングルール 46.0kg契約ワンマッチ 3分3R",
        fighterA: "上田樹那",
        fighterB: "北野ヒナタ",
        winner: "北野ヒナタ",
        method: "3R終了 判定0-3",
      },
      {
        weightClass: "第3試合 キックボクシングルール 62.0kg契約ワンマッチ 3分3R",
        fighterA: "勇志",
        fighterB: "麻太郎",
        winner: "勇志",
        method: "3R終了 判定3-0",
      },
      {
        weightClass: "第4試合 MMA特別ルール 57.0kg契約ワンマッチ 5分2R",
        fighterA: "濱口奏琉",
        fighterB: "砂田華杜",
        winner: "濱口奏琉",
        method: "1R 2:33 TKO（パウンド）",
      },
      {
        weightClass: "第1試合 MMAルール 66.0kg契約ワンマッチ 5分3R",
        fighterA: "中川皓貴",
        fighterB: "ジェイク・ウィルキンス",
        winner: "中川皓貴",
        method: "3R終了 判定3-0 (29-27、29-27、29-27)",
      },
      {
        weightClass: "第2試合 MMAルール 57.0kg契約ワンマッチ 5分3R",
        fighterA: "飴山聖也",
        fighterB: "平本丈",
        winner: "平本丈",
        method: "2R 0:27 リアネイキッドチョーク",
      },
      {
        weightClass: "第3試合 MMAルール 62.0kg契約ワンマッチ 5分3R",
        fighterA: "ジョリー",
        fighterB: "児玉兼慎",
        winner: "ジョリー",
        method: "1R 1:11 腕ひしぎ十字固め",
      },
      {
        weightClass: "第4試合 MMAルール 61.0kg契約ワンマッチ 5分3R",
        fighterA: "ダイキ・ライトイヤー",
        fighterB: "梅野源治",
        winner: "ダイキ・ライトイヤー",
        method: "1R 2:37 三角締め",
      },
      {
        weightClass: "第5試合 MMAルール 66.0kg契約ワンマッチ 5分3R",
        fighterA: "松嶋こよみ",
        fighterB: "ライアン・カファロ",
        winner: "ライアン・カファロ",
        method: "3R 2:23 ドラゴンスリーパー",
      },
      {
        weightClass: "第6試合 MMAルール 71.0kg契約ワンマッチ 5分3R",
        fighterA: "雑賀“ヤン坊”達也",
        fighterB: "宇佐美正パトリック",
        winner: "宇佐美正パトリック",
        method: "1R 1:38 TKO（左フック→サッカーボールキック）",
      },
      {
        weightClass: "第7試合 MMAルール 51.0kg契約ワンマッチ 5分3R",
        fighterA: "ケイト・ロータス",
        fighterB: "ケイティ・ペレス",
        winner: "ケイト・ロータス",
        method: "3R終了 判定3-0 (30-27、30-27、30-27)",
      },
      {
        weightClass: "第8試合 MMAルール 61.0kg契約ワンマッチ 5分3R",
        fighterA: "太田忍",
        fighterB: "金太郎",
        winner: "太田忍",
        method: "2R 4:25 肩固め",
      },
      {
        weightClass: "第9試合 MMAルール 66.0kg契約ワンマッチ 5分3R",
        fighterA: "高木凌",
        fighterB: "リー・カイウェン",
        winner: "高木凌",
        method: "1R 1:38 TKO（右ストレート→パウンド）",
      },
      {
        weightClass: "第10試合 スタンディングバウト特別ルール 無差別級ワンマッチ 3分3R",
        fighterA: "平本蓮",
        fighterB: "皇治",
        winner: null,
        method: "3R終了 判定なし ドロー",
      },
      {
        weightClass: "RIZINライト級タイトルマッチ",
        fighterA: "イルホム・ノジモフ",
        fighterB: "ルイス・グスタボ",
        winner: "ルイス・グスタボ",
        method: "1R 2:08 TKO（右フック→パウンド） ※グスタボが第3代王座獲得に成功。",
      },
    ],
  },
  {
    slug: "rizin-landmark-13",
    org: "rizin",
    eventName: "RIZIN LANDMARK 13",
    date: "2026-04-12",
    venue: "マリンメッセ福岡A館",
    sourceUrl: "https://ja.wikipedia.org/wiki/RIZIN_LANDMARK_13",
    fights: [
      {
        weightClass: "第1試合 キックボクシングルール 57.0kg契約ワンマッチ 3分3R",
        fighterA: "今村流星",
        fighterB: "YU-KI",
        winner: "今村流星",
        method: "2R 0:58 TKO (レフェリーストップ)",
      },
      {
        weightClass: "第2試合 MMA特別ルール 71.0kg契約ワンマッチ 5分2R",
        fighterA: "大木良太",
        fighterB: "荒井銀二",
        winner: "大木良太",
        method: "2R終了 判定3-0",
      },
      {
        weightClass: "第3試合 MMA特別ルール 61.0kg契約ワンマッチ 5分2R",
        fighterA: "山﨑鼓大",
        fighterB: "有松朋晃",
        winner: "有松朋晃",
        method: "1R 4:37 TKO (パウンド)",
      },
      {
        weightClass: "第4試合 MMA特別ルール 57.0kg契約ワンマッチ 5分2R",
        fighterA: "八尋大輝",
        fighterB: "岡本瞬",
        winner: "岡本瞬",
        method: "2R終了 判定0-3",
      },
      {
        weightClass: "第1試合 MMAルール 61.0kg契約ワンマッチ 5分3R",
        fighterA: "井上聖矢",
        fighterB: "宮川日向",
        winner: "宮川日向",
        method: "3R終了 判定0-3 (28-29、28-29、27-30)",
      },
      {
        weightClass: "第2試合 MMAルール 57.0kg契約ワンマッチ 5分3R",
        fighterA: "本田良介",
        fighterB: "火の鳥",
        winner: "火の鳥",
        method: "1R 4:59 TKO（右ストレート→パウンド）",
      },
      {
        weightClass: "第3試合 MMAルール 71.0kg契約ワンマッチ 5分3R",
        fighterA: "ヌルハン・ズマガジー",
        fighterB: "天弥",
        winner: "ヌルハン・ズマガジー",
        method: "3R終了 判定3-0 (29-26、30-25、29-26)",
      },
      {
        weightClass: "第4試合 MMAルール 66.0kg契約ワンマッチ 5分3R",
        fighterA: "摩嶋一整",
        fighterB: "ジェームズ・ギャラガー",
        winner: "摩嶋一整",
        method: "3R 2:35 肩固め",
      },
      {
        weightClass: "第5試合 MMAルール 49.0kg契約ワンマッチ 5分3R",
        fighterA: "浜崎朱加",
        fighterB: "ナターシャ・クジュティナ",
        winner: "ナターシャ・クジュティナ",
        method: "1R 4:55 腕ひしぎ十字固め",
      },
      {
        weightClass: "第6試合 MMAルール 57.0kg契約ワンマッチ 5分3R",
        fighterA: "神龍誠",
        fighterB: "エンカジムーロ・ズールー",
        winner: "神龍誠",
        method: "1R 2:52 アームロック",
      },
      {
        weightClass: "第7試合 キックボクシングルール 66.0kg契約ワンマッチ 3分3R",
        fighterA: "朝久泰央",
        fighterB: "シンパヤック・ハマジム",
        winner: "朝久泰央",
        method: "1R 1:45 KO (右ボディストレート)",
      },
      {
        weightClass: "第8試合 MMAルール 61.0kg契約ワンマッチ 5分3R",
        fighterA: "福田龍彌",
        fighterB: "アジズベク・テミロフ",
        winner: "アジズベク・テミロフ",
        method: "2R 1:40 KO（右フック）",
      },
      {
        weightClass: "第10試合 MMAルール 71.0kg契約ワンマッチ 5分3R",
        fighterA: "堀江圭功",
        fighterB: "パトリッキー・ピットブル",
        winner: "堀江圭功",
        method: "3R終了 判定2-1 (28-29、30-27、29-28)",
      },
      {
        weightClass: "第8代RIZINバンタム級王座決定戦",
        fighterA: "ダニー・サバテロ",
        fighterB: "後藤丈治",
        winner: "ダニー・サバテロ",
        method: "3R終了 判定3-0 (30ｰ27、30ｰ26、30ｰ27)",
      },
      {
        weightClass: "RIZINフェザー級タイトルマッチ",
        fighterA: "ラジャブアリ・シェイドゥラエフ",
        fighterB: "久保優太",
        winner: "ラジャブアリ・シェイドゥラエフ",
        method: "1R 4:13 TKO（パウンド） ※シェイドゥラエフが3度目の王座防衛に成功。",
      },
    ],
  },
  {
    slug: "rizin-landmark-14",
    org: "rizin",
    eventName: "RIZIN LANDMARK 14",
    date: "2026-06-06",
    venue: "ゼビオアリーナ仙台",
    sourceUrl: "https://ja.wikipedia.org/wiki/RIZIN_LANDMARK_14",
    fights: [
      {
        weightClass: "第1試合 キックボクシングルール 62.0kg契約ワンマッチ 3分3R",
        fighterA: "岩城悠介",
        fighterB: "中泉翔",
        winner: "岩城悠介",
        method: "3R 0:47 KO (飛び膝蹴り)",
      },
      {
        weightClass: "第2試合 キックボクシングルール 56.5kg契約ワンマッチ 3分3R",
        fighterA: "赤平大治",
        fighterB: "内田晶",
        winner: "内田晶",
        method: "3R終了 判定0-3",
      },
      {
        weightClass: "第3試合 キックボクシングルール 67.5kg契約ワンマッチ 3分3R",
        fighterA: "齋藤紘也",
        fighterB: "TAaaaCHAN",
        winner: "齋藤紘也",
        method: "1R 1:25 TKO (3ノックダウン)",
      },
      {
        weightClass: "第4試合 MMA特別ルール 57.0kg契約ワンマッチ 5分2R",
        fighterA: "颯斗",
        fighterB: "湯浅帝蓮",
        winner: "颯斗",
        method: "2R終了 判定2-1 (20-18、20-18、19-19 (マスト：湯浅))",
      },
      {
        weightClass: "第1試合 MMAルール 61.0kg契約ワンマッチ 5分3R",
        fighterA: "赤田功輝",
        fighterB: "井上聖矢",
        winner: "井上聖矢",
        method: "3R 0:28 TKO（左フック→パウンド）",
      },
      {
        weightClass: "第2試合 MMAルール 66.0kg契約ワンマッチ 5分3R",
        fighterA: "直樹",
        fighterB: "黒井海成",
        winner: "直樹",
        method: "1R 3:37 TKO（左膝蹴り→パウンド）",
      },
      {
        weightClass: "第3試合 MMAルール 57.0kg契約ワンマッチ 5分3R",
        fighterA: "冨澤大智",
        fighterB: "加藤瑠偉",
        winner: "冨澤大智",
        method: "1R 4:37 TKO（グラウンドでの肘打ち）",
      },
      {
        weightClass: "第4試合 MMAルール 71.0kg契約ワンマッチ 5分3R",
        fighterA: "矢地祐介",
        fighterB: "ISAO",
        winner: "矢地祐介",
        method: "3R終了 判定3-0 (29-28、29-28、29-28)",
      },
      {
        weightClass: "第5試合 MMAルール 71.1kg契約ワンマッチ 5分3R",
        fighterA: "“ブラックパンサー”ベイノア",
        fighterB: "芳賀ビラル海",
        winner: "“ブラックパンサー”ベイノア",
        method: "2R 0:10 KO（左ハイキック）",
      },
      {
        weightClass: "第6試合 MMAルール 121.2kg契約ワンマッチ 5分3R",
        fighterA: "酒井リョウ",
        fighterB: "貴賢神",
        winner: "貴賢神",
        method: "1R 1:16 TKO（右ストレート→パウンド）",
      },
      {
        weightClass: "第7試合 MMAルール 59.0kg契約ワンマッチ 5分3R",
        fighterA: "元谷友貴",
        fighterB: "トニー・ララミー",
        winner: "トニー・ララミー",
        method: "3R終了 判定0-3 (26-30、26-30、25-30)",
      },
      {
        weightClass: "RIZINフライ級タイトルマッチ",
        fighterA: "扇久保博正",
        fighterB: "神龍誠",
        winner: "神龍誠",
        method: "3R終了 判定0-3 (27-30、27-30、28-29) ※神龍が第3代王座獲得に成功。",
      },
    ],
  },
];

export function getEventResult(slug: string): EventResult | undefined {
  return EVENT_RESULTS.find((e) => e.slug === slug);
}
