import { SourceKey } from "./sources";

export interface FightResult {
  weightClass: string;
  fighterA: string;
  fighterB: string;
  winner: string | null; // null = 未定/不明、"引き分け"/"中止"/"NC" = 該当結果
  method: string;
  round?: string;
}

export interface EventResult {
  slug: string;
  org: SourceKey;
  eventName: string;
  date: string; // YYYY-MM-DD
  venue?: string;
  sourceUrl?: string;
  fights: FightResult[];
}

export const EVENT_RESULTS: EventResult[] = [
  {
    slug: "pancrase-363",
    org: "pancrase",
    eventName: "PANCRASE 363",
    date: "2026-06-28",
    venue: "東京・ニューピアホール",
    sourceUrl: "https://www.pancrase.co.jp/data/result/2026/0628.html",
    fights: [
      {
        weightClass: "フェザー級暫定王座決定戦",
        fighterA: "オタベク・ラジャボフ",
        fighterB: "木下尚祐",
        winner: "オタベク・ラジャボフ",
        method: "三角絞め",
        round: "3R 2:45",
      },
      {
        weightClass: "ライト級",
        fighterA: "粕谷優介",
        fighterB: "神谷大智",
        winner: "神谷大智",
        method: "TKO（グラウンドパンチ）",
        round: "2R 3:39",
      },
      {
        weightClass: "フライ級",
        fighterA: "谷村泰嘉",
        fighterB: "眞藤源太",
        winner: "眞藤源太",
        method: "ニンジャチョーク",
        round: "3R 4:25",
      },
      {
        weightClass: "ストロー級",
        fighterA: "氏原快聖",
        fighterB: "寺岡拓永",
        winner: "引き分け",
        method: "判定（0-0）",
        round: "3R 5:00",
      },
      {
        weightClass: "フェザー級",
        fighterA: "亀井晨佑",
        fighterB: "畠山佑介",
        winner: "畠山佑介",
        method: "TKO（グラウンドパンチ）",
        round: "3R 3:50",
      },
      {
        weightClass: "ウェルター級",
        fighterA: "武者光太郎",
        fighterB: "萱沼哲平",
        winner: "武者光太郎",
        method: "TKO（グラウンドパンチ）",
        round: "2R 2:50",
      },
      {
        weightClass: "ライト級",
        fighterA: "下山楓人",
        fighterB: "宮本樹",
        winner: "宮本樹",
        method: "TKO（グラウンドパンチ）",
        round: "2R 4:13",
      },
      {
        weightClass: "バンタム級",
        fighterA: "筑紫淳平",
        fighterB: "鈴木優太郎",
        winner: "筑紫淳平",
        method: "裸絞め",
        round: "1R 1:12",
      },
      {
        weightClass: "バンタム級",
        fighterA: "増田蓮央",
        fighterB: "村社大河",
        winner: "増田蓮央",
        method: "フロントチョーク",
        round: "1R 2:36",
      },
      {
        weightClass: "バンタム級",
        fighterA: "抜井祥輝",
        fighterB: "近藤優馬",
        winner: "近藤優馬",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "小野智也",
        fighterB: "前川慧",
        winner: "中止",
        method: "試合中止（計量失格）",
      },
    ],
  },
  {
    slug: "shooto-torao-2026",
    org: "shooto",
    eventName: "Lemino修斗TORAO",
    date: "2026-06-28",
    venue: "福岡・アクロス福岡イベントホール",
    sourceUrl: "https://j-shooto.com/2026/06/28/post-50832/",
    fights: [
      {
        weightClass: "フェザー級（-65.8kg）",
        fighterA: "TOMA",
        fighterB: "田中半蔵",
        winner: "TOMA",
        method: "TKO",
        round: "2R 1:09",
      },
      {
        weightClass: "バンタム級（61.2kg）",
        fighterA: "野瀬翔平",
        fighterB: "青柳洸志",
        winner: "野瀬翔平",
        method: "肩固め",
        round: "1R 3:19",
      },
      {
        weightClass: "フライ級（-56.7kg）",
        fighterA: "上田将年",
        fighterB: "打威致",
        winner: "打威致",
        method: "TKO",
        round: "1R 3:51",
      },
      {
        weightClass: "フェザー級（-65.8kg）",
        fighterA: "ナイン・ダイネッシュ",
        fighterB: "久保村佳照",
        winner: "ナイン・ダイネッシュ",
        method: "TKO",
        round: "1R 1:13",
      },
      {
        weightClass: "ストロー級（52.2kg）",
        fighterA: "緑真作",
        fighterB: "梅木勇徳",
        winner: "梅木勇徳",
        method: "判定（0-3）",
      },
      {
        weightClass: "フェザー級（-65.8kg）",
        fighterA: "本松要",
        fighterB: "柿原翔太",
        winner: "柿原翔太",
        method: "KO",
        round: "2R 2:08",
      },
      {
        weightClass: "フェザー級（-65.8kg）",
        fighterA: "山田龍馬",
        fighterB: "深町巧",
        winner: "深町巧",
        method: "裸絞め",
        round: "2R 2:02",
      },
      {
        weightClass: "フライ級（-56.7kg）",
        fighterA: "高宮稜",
        fighterB: "竹本葵天",
        winner: "引き分け",
        method: "判定（1-0）",
      },
      {
        weightClass: "ストロー級（52.2kg）",
        fighterA: "新誠",
        fighterB: "佐野光輝",
        winner: "佐野光輝",
        method: "三角絞め",
        round: "1R 2:19",
      },
      {
        weightClass: "ストロー級（52.2kg）",
        fighterA: "和氣輝央",
        fighterB: "高井裕翔",
        winner: "高井裕翔",
        method: "KO",
        round: "1R 0:28",
      },
    ],
  },
  {
    slug: "pancrase-362",
    org: "pancrase",
    eventName: "PANCRASE 362",
    date: "2026-05-31",
    venue: "東京・立川ステージガーデン",
    sourceUrl: "https://www.pancrase.co.jp/data/result/2026/0531.html",
    fights: [
      {
        weightClass: "King of Pancraseフライ級王座決定戦",
        fighterA: "時田隆成",
        fighterB: "岸田宙大",
        winner: "時田隆成",
        method: "判定（2-1）",
        round: "5R 5:00",
      },
      {
        weightClass: "バンタム級暫定王座決定戦",
        fighterA: "宮城成歩滝",
        fighterB: "山口怜臣",
        winner: "宮城成歩滝",
        method: "判定（0-3）",
        round: "5R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "濱田巧",
        fighterB: "ジョセフ・カマチョ",
        winner: "濱田巧",
        method: "フロントチョーク",
        round: "2R 1:05",
      },
      {
        weightClass: "フェザー級",
        fighterA: "三宅輝砂",
        fighterB: "遠藤来生",
        winner: "三宅輝砂",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "ライト級",
        fighterA: "鈴木慈也",
        fighterB: "平信一",
        winner: "鈴木慈也",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "バンタム級",
        fighterA: "バラカトゥロ・アサドゥラエフ",
        fighterB: "矢澤諒",
        winner: "バラカトゥロ・アサドゥラエフ",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "キャッチウェイト",
        fighterA: "時田一生",
        fighterB: "藤野武",
        winner: "時田一生",
        method: "裸絞め",
        round: "1R 2:17",
      },
      {
        weightClass: "フェザー級",
        fighterA: "福里凱亜",
        fighterB: "沢木純也",
        winner: "福里凱亜",
        method: "判定（3-0）",
        round: "3R 5:00",
      },
      {
        weightClass: "バンタム級",
        fighterA: "平澤宏樹",
        fighterB: "髙木徳三",
        winner: "平澤宏樹",
        method: "ツイスター",
        round: "2R 1:30",
      },
      {
        weightClass: "バンタム級",
        fighterA: "谷村泰和",
        fighterB: "水島和磨",
        winner: "谷村泰和",
        method: "判定（2-1）",
        round: "3R 5:00",
      },
      {
        weightClass: "バンタム級",
        fighterA: "石原健流",
        fighterB: "小山敬司",
        winner: "石原健流",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "齋藤楼貴",
        fighterB: "嶺大基",
        winner: "齋藤楼貴",
        method: "判定（2-1）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "天坂匡孝",
        fighterB: "稲垣祐司",
        winner: "天坂匡孝",
        method: "肩固め",
        round: "2R 2:07",
      },
      {
        weightClass: "フライ級",
        fighterA: "獅道",
        fighterB: "佐々木裕亮",
        winner: "獅道",
        method: "腕ひしぎ十字固め",
        round: "1R 1:44",
      },
    ],
  },
  {
    slug: "pancrase-361",
    org: "pancrase",
    eventName: "PANCRASE 361",
    date: "2026-03-14",
    venue: "神奈川・横浜武道館",
    sourceUrl: "https://www.pancrase.co.jp/data/result/2026/0314.html",
    fights: [
      {
        weightClass: "ライト級王座決定戦",
        fighterA: "雑賀ヤン坊達也",
        fighterB: "ラファエル・バルボーザ",
        winner: "ラファエル・バルボーザ",
        method: "TKO（目元の負傷）",
        round: "2R 4:41",
      },
      {
        weightClass: "女子フライ級王座決定戦",
        fighterA: "杉山しずか",
        fighterB: "和田綾音",
        winner: "杉山しずか",
        method: "判定（3-0）",
        round: "5R 5:00",
      },
      {
        weightClass: "ストロー級王座決定戦",
        fighterA: "船田電池",
        fighterB: "宮澤雄大",
        winner: "宮澤雄大",
        method: "判定（1-2）",
        round: "5R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "伊藤盛一郎",
        fighterB: "ジョセフ・カマチョ",
        winner: "NC",
        method: "ノーコンテスト",
      },
      {
        weightClass: "フライ級",
        fighterA: "大塚智貴",
        fighterB: "猿飛流",
        winner: "猿飛流",
        method: "TKO（グラウンドパンチ）",
        round: "2R 0:25",
      },
      {
        weightClass: "ウェルター級",
        fighterA: "内藤由良",
        fighterB: "ガブリエル・レヴェン",
        winner: "内藤由良",
        method: "判定（3-0）",
        round: "3R 5:00",
      },
      {
        weightClass: "バンタム級",
        fighterA: "山木麻弥",
        fighterB: "荒田大輝",
        winner: "荒田大輝",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "ライト級",
        fighterA: "神谷大智",
        fighterB: "葛西和希",
        winner: "神谷大智",
        method: "判定（2-1）",
        round: "3R 5:00",
      },
      {
        weightClass: "70kg契約",
        fighterA: "透暉鷹",
        fighterB: "ギリェルメ・ナカガワ",
        winner: "透暉鷹",
        method: "TKO（グラウンドパンチ）",
        round: "1R 4:33",
      },
      {
        weightClass: "フェザー級",
        fighterA: "木下尚祐",
        fighterB: "シン・ジェヨン",
        winner: "木下尚祐",
        method: "判定（3-0）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "岸田宙大",
        fighterB: "眞藤源太",
        winner: "岸田宙大",
        method: "三角絞め",
        round: "1R 2:38",
      },
      {
        weightClass: "フェザー級",
        fighterA: "岡田拓真",
        fighterB: "清水博人",
        winner: "清水博人",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
      {
        weightClass: "フライ級",
        fighterA: "菅歩夢",
        fighterB: "谷村泰嘉",
        winner: "菅歩夢",
        method: "フロントチョーク",
        round: "1R 1:06",
      },
      {
        weightClass: "ミドル級",
        fighterA: "平田旭",
        fighterB: "林源平",
        winner: "平田旭",
        method: "TKO（立ち技パンチ）",
        round: "1R 3:17",
      },
      {
        weightClass: "ストロー級",
        fighterA: "リトル",
        fighterB: "佐々木瞬真",
        winner: "佐々木瞬真",
        method: "判定（0-3）",
        round: "3R 5:00",
      },
    ],
  },
  {
    slug: "deep-osaka-impact-2026-3rd-round",
    org: "deep",
    eventName: "DEEP OSAKA IMPACT 2026 3rd ROUND",
    date: "2026-06-21",
    venue: "錦秀会 住吉区民センター大ホール（大阪）",
    sourceUrl:
      "https://www.deep2001.com/deep%e8%a5%bf%e6%97%a5%e6%9c%ac%e3%83%90%e3%83%b3%e3%82%bf%e3%83%a0%e7%b4%9agp%ef%bc%91%e5%9b%9e%e6%88%a6%e3%80%81%e6%a0%97%e5%b1%b1%e8%91%b5%e3%81%8c%e5%9b%bd%e9%9a%9b%e6%88%a6%e3%81%ab%e6%8c%91/",
    fights: [
      {
        weightClass: "DEEP JEWELSフライ級",
        fighterA: "栗山葵",
        fighterB: "サラ・マームード",
        winner: "サラ・マームード",
        method: "判定（1-2）",
      },
      {
        weightClass: "DEEPライト級",
        fighterA: "Street♡★Bob洸助",
        fighterB: "河坂修斗",
        winner: "Street♡★Bob洸助",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "小川道的",
        fighterB: "澤田龍美",
        winner: "小川道的",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "麦谷悠成",
        fighterB: "杉映都",
        winner: "麦谷悠成",
        method: "裸絞め",
        round: "2R 1:37",
      },
      {
        weightClass: "DEEP 68kg契約",
        fighterA: "田中雄大",
        fighterB: "田中壱季",
        winner: "田中雄大",
        method: "裸絞め",
        round: "1R 4:04",
      },
      {
        weightClass: "DEEPストロー級",
        fighterA: "武蔵",
        fighterB: "小柳泰牙",
        winner: "武蔵",
        method: "裸絞め",
        round: "1R 4:34",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "澄斗",
        fighterB: "秋田良隆",
        winner: "澄斗",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "Fernando",
        fighterB: "カーレッジユウキ",
        winner: "Fernando",
        method: "裸絞め",
        round: "2R 2:43",
      },
      {
        weightClass: "DEEP JEWELSストロー級",
        fighterA: "橋本葵",
        fighterB: "渡辺真央",
        winner: "渡辺真央",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEP JEWELS 50kg契約",
        fighterA: "あー子",
        fighterB: "西口日奈子",
        winner: "西口日奈子",
        method: "判定（1-2）",
      },
      {
        weightClass: "DEEPウェルター級",
        fighterA: "山本怜旺",
        fighterB: "居谷匠真",
        winner: "居谷匠真",
        method: "TKO",
        round: "2R 0:35",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "加藤憂也",
        fighterB: "大島伊玖都",
        winner: "加藤憂也",
        method: "TKO",
        round: "1R 2:54",
      },
      {
        weightClass: "DEEP西日本バンタム級GP 1回戦",
        fighterA: "前薗渓",
        fighterB: "木下竜馬",
        winner: "前薗渓",
        method: "裸絞め",
        round: "3R 1:35",
      },
      {
        weightClass: "DEEP西日本バンタム級GP 1回戦",
        fighterA: "切嶋龍輝",
        fighterB: "寺崎昇龍",
        winner: "切嶋龍輝",
        method: "TKO",
        round: "2R 5:00",
      },
      {
        weightClass: "DEEP西日本バンタム級GP 1回戦",
        fighterA: "大空斗",
        fighterB: "谷岡祐樹",
        winner: "大空斗",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEP西日本バンタム級GP 1回戦",
        fighterA: "MG眞介",
        fighterB: "みやび",
        winner: "MG眞介",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPメガトン級",
        fighterA: "稲田将",
        fighterB: "西川将輝",
        winner: "稲田将",
        method: "TKO",
        round: "2R 3:31",
      },
      {
        weightClass: "DEEPウェルター級",
        fighterA: "虎鉄",
        fighterB: "窪田大羅",
        winner: "虎鉄",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEP JEWELSフライ級",
        fighterA: "鈴木QPまい",
        fighterB: "ルリ・サンシャイン",
        winner: "ルリ・サンシャイン",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "古根川充",
        fighterB: "権藤大剛",
        winner: "古根川充",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEPメガトン級",
        fighterA: "ステファン“スマッシュ”",
        fighterB: "酒井天佑",
        winner: "ステファン“スマッシュ”",
        method: "TKO",
        round: "1R 1:19",
      },
    ],
  },
  {
    slug: "deep-nagoya-impact-2026-2nd-round",
    org: "deep",
    eventName: "DEEP NAGOYA IMPACT 2026 2nd ROUND公武堂ファイト",
    date: "2026-06-14",
    venue: "刈谷市産業振興センター あいおいホール",
    sourceUrl:
      "https://www.deep2001.com/%e3%83%a1%e3%82%a4%e3%83%b3%e3%81%aftatsumi%e3%81%ae%e5%be%a9%e5%b8%b0%e6%88%a6%e3%80%81%e3%80%8edeep-nagoya-impact-2026-2nd-round%e3%80%8f%e3%81%ae%e8%a9%a6%e5%90%88%e7%b5%90%e6%9e%9c/",
    fights: [
      {
        weightClass: "DEEPフェザー級",
        fighterA: "アジョウ海翔",
        fighterB: "TATSUMI",
        winner: "アジョウ海翔",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPウェルター級",
        fighterA: "浅野功",
        fighterB: "カーン・ソグズ",
        winner: "浅野功",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "時任琉空",
        fighterB: "鈴木幹也",
        winner: "時任琉空",
        method: "腕ひしぎ十字固め",
        round: "1R 4:32",
      },
      {
        weightClass: "DEEPストロー級",
        fighterA: "鶴人",
        fighterB: "上村稜真",
        winner: "鶴人",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "ビオレス熊座",
        fighterB: "中川内隼人",
        winner: "ビオレス熊座",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "大澤昊",
        fighterB: "ケヴィン・ギノザ",
        winner: "大澤昊",
        method: "判定（0-3）",
      },
      {
        weightClass: "MAXFC JAPAN -48kg契約",
        fighterA: "ユリカ",
        fighterB: "パク・ソヨン",
        winner: "ユリカ",
        method: "TKO（2R終了時）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "吉田翼",
        fighterB: "SHOYA",
        winner: "吉田翼",
        method: "裸絞め",
        round: "2R 2:38",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "杉村翔馬",
        fighterB: "石田ガリットカツヤ",
        winner: "杉村翔馬",
        method: "判定（0-3）",
      },
      {
        weightClass: "MAXFC JAPAN -54kg契約",
        fighterA: "アカリ",
        fighterB: "チェ・ウンジ",
        winner: "アカリ",
        method: "TKO（延長0:30）",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "三塚祐介",
        fighterB: "永井寛人",
        winner: "三塚祐介",
        method: "腕ひしぎ十字固め",
        round: "1R 3:28",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "橋上颯馬",
        fighterB: "古市陸",
        winner: "橋上颯馬",
        method: "裸絞め",
        round: "1R 2:42",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "椿薫",
        fighterB: "青城翔",
        winner: "椿薫",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "山田優太",
        fighterB: "川端凛人",
        winner: "山田優太",
        method: "判定（3-0）",
      },
    ],
  },
  {
    slug: "deep-jewels-52",
    org: "deep",
    eventName: "DEEP JEWELS 52",
    date: "2026-02-23",
    venue: "後楽園ホール",
    sourceUrl: "https://www.deep2001.com/deep-jewels-52/",
    fights: [
      {
        weightClass: "DEEP JEWELS 50kg以下 KICKルール",
        fighterA: "島村優花",
        fighterB: "中澤諒香",
        winner: "島村優花",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEP JEWELS 49kg以下",
        fighterA: "横瀬美久",
        fighterB: "渡邊花美",
        winner: "中止",
        method: "試合中止（計量失格）",
      },
      {
        weightClass: "DEEP JEWELSストロー級 KICKルール",
        fighterA: "坂本瑠華",
        fighterB: "ダイナマイト♡ユラ",
        winner: "坂本瑠華",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEP JEWELSストロー級",
        fighterA: "横瀬友愛",
        fighterB: "岡美紀",
        winner: "横瀬友愛",
        method: "ヴォンフルーチョーク",
        round: "2R 3:42",
      },
      {
        weightClass: "DEEP JEWELSストロー級",
        fighterA: "桐生祐子",
        fighterB: "堀井かりん",
        winner: "桐生祐子",
        method: "腕ひしぎ十字固め",
        round: "1R 4:29",
      },
      {
        weightClass: "DEEP JEWELS 49kg以下",
        fighterA: "竹林エル",
        fighterB: "海咲イルカ",
        winner: "竹林エル",
        method: "TKO",
        round: "2R 1:08",
      },
      {
        weightClass: "DEEP JEWELSストロー級",
        fighterA: "万智",
        fighterB: "キム・ダンビ",
        winner: "万智",
        method: "フロントチョーク",
        round: "1R 0:58",
      },
      {
        weightClass: "DEEP JEWELSバンタム級王座決定戦",
        fighterA: "百湖",
        fighterB: "樹季",
        winner: "百湖",
        method: "TKO",
        round: "2R 3:13",
      },
    ],
  },
  {
    slug: "deep-130-impact",
    org: "deep",
    eventName: "DEEP 130 IMPACT",
    date: "2026-03-20",
    venue: "後楽園ホール",
    sourceUrl: "https://www.deep2001.com/deep-130-impact/",
    fights: [
      {
        weightClass: "DEEPライト級",
        fighterA: "鈴木大晟",
        fighterB: "奥村歩生",
        winner: "鈴木大晟",
        method: "TKO",
        round: "1R 3:25",
      },
      {
        weightClass: "DEEPライト級",
        fighterA: "ケンシロウ",
        fighterB: "中谷優我",
        winner: "ケンシロウ",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "日比野純也",
        fighterB: "山本有人",
        winner: "山本有人",
        method: "失格",
        round: "1R 0:20",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "魚井フルスイング",
        fighterB: "寺崎昇龍",
        winner: "寺崎昇龍",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "木下カラテ",
        fighterB: "直樹",
        winner: "直樹",
        method: "リアネイキッドチョーク",
        round: "1R 0:22",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "五明宏人",
        fighterB: "椿飛鳥",
        winner: "椿飛鳥",
        method: "TKO",
        round: "2R 4:38",
      },
      {
        weightClass: "DEEPフライ級",
        fighterA: "関原翔",
        fighterB: "力也",
        winner: "力也",
        method: "判定（1-2）",
      },
      {
        weightClass: "DEEPメガトン級",
        fighterA: "酒井リョウ",
        fighterB: "荒東英貴",
        winner: "酒井リョウ",
        method: "TKO",
        round: "1R 3:26",
      },
      {
        weightClass: "DEEPウェルター級タイトルマッチ",
        fighterA: "嶋田伊吹",
        fighterB: "ストラッサー起一",
        winner: "嶋田伊吹",
        method: "リアネイキッドチョーク",
        round: "1R 3:44",
      },
      {
        weightClass: "DEEPライト級タイトルマッチ",
        fighterA: "大原樹理",
        fighterB: "倉本大悟",
        winner: "NC",
        method: "ノーコンテスト（ローブロー）",
        round: "1R 1:29",
      },
    ],
  },
  {
    slug: "deep-131-impact",
    org: "deep",
    eventName: "DEEP 131 IMPACT",
    date: "2026-05-04",
    venue: "横浜BUNTAI",
    sourceUrl: "https://www.deep2001.com/deep-131-impact/",
    fights: [
      {
        weightClass: "DEEPフェザー級",
        fighterA: "杉野亜蓮",
        fighterB: "ダイヤ",
        winner: "杉野亜蓮",
        method: "フロントチョーク",
        round: "2R 0:36",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "諏訪部哲平",
        fighterB: "石坂空志",
        winner: "石坂空志",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPメガトン級",
        fighterA: "誠悟",
        fighterB: "タンク内藤",
        winner: "タンク内藤",
        method: "TKO",
        round: "1R 0:36",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "窪田泰斗",
        fighterB: "小崎連",
        winner: "小崎連",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPメガトン級",
        fighterA: "赤沢幸典",
        fighterB: "金田一孝介",
        winner: "赤沢幸典",
        method: "TKO",
        round: "1R 4:36",
      },
      {
        weightClass: "DEEPライト級",
        fighterA: "泉武志",
        fighterB: "山本颯志",
        winner: "泉武志",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEPフェザー級",
        fighterA: "中村大介",
        fighterB: "狩野優",
        winner: "狩野優",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPバンタム級",
        fighterA: "瀧澤謙太",
        fighterB: "雅駿介",
        winner: "瀧澤謙太",
        method: "TKO",
        round: "3R 2:22",
      },
      {
        weightClass: "DEEP 59kg以下",
        fighterA: "猿寿健太",
        fighterB: "関原翔",
        winner: "関原翔",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPウェルター級",
        fighterA: "阿部大治",
        fighterB: "角野晃平",
        winner: "角野晃平",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEPストロー級タイトルマッチ",
        fighterA: "杉山空",
        fighterB: "知名昴海",
        winner: "知名昴海",
        method: "判定（0-5）",
      },
      {
        weightClass: "DEEPバンタム級暫定王座決定戦",
        fighterA: "平松翔",
        fighterB: "鹿志村仁之介",
        winner: "鹿志村仁之介",
        method: "TKO",
        round: "1R 0:16",
      },
      {
        weightClass: "DEEPフライ級タイトルマッチ",
        fighterA: "村元友太郎",
        fighterB: "力也",
        winner: "村元友太郎",
        method: "膝十字",
        round: "2R 4:48",
      },
      {
        weightClass: "DEEPライト級タイトルマッチ",
        fighterA: "大原樹理",
        fighterB: "倉本大悟",
        winner: "大原樹理",
        method: "TKO",
        round: "1R 2:19",
      },
      {
        weightClass: "DEEPフェザー級暫定王座決定戦",
        fighterA: "牛久絢太郎",
        fighterB: "水野新太",
        winner: "水野新太",
        method: "判定（0-5）",
      },
    ],
  },
  {
    slug: "deep-jewels-53",
    org: "deep",
    eventName: "DEEP JEWELS 53",
    date: "2026-05-24",
    sourceUrl: "https://www.deep2001.com/deep-jewels-52-2/",
    fights: [
      {
        weightClass: "DEEP JEWELS 53kg以下",
        fighterA: "SAAYA",
        fighterB: "渡辺真央",
        winner: "SAAYA",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEP JEWELS 58kg以下",
        fighterA: "鈴木遥",
        fighterB: "田川真帆",
        winner: "鈴木遥",
        method: "判定（3-0）",
      },
      {
        weightClass: "DEEP JEWELSミクロ級",
        fighterA: "古林礼名",
        fighterB: "大井すず",
        winner: "大井すず",
        method: "判定（0-3）",
      },
      {
        weightClass: "DEEP JEWELS 65kg以下",
        fighterA: "樹季",
        fighterB: "Te-a",
        winner: "樹季",
        method: "TKO",
        round: "1R 3:44",
      },
      {
        weightClass: "DEEP JEWELS 49kg以下",
        fighterA: "彩綺",
        fighterB: "abbie",
        winner: "彩綺",
        method: "TKO",
        round: "1R 0:32",
      },
      {
        weightClass: "DEEP JEWELSストロー級",
        fighterA: "桐生祐子",
        fighterB: "月井隼南",
        winner: "桐生祐子",
        method: "TKO",
        round: "2R 1:37",
      },
      {
        weightClass: "DEEP JEWELSストロー級",
        fighterA: "ののか",
        fighterB: "キム・ソユル",
        winner: "ののか",
        method: "判定（2-1）",
      },
      {
        weightClass: "DEEP JEWELS 49kg以下",
        fighterA: "竹林エル",
        fighterB: "イ・イェジ",
        winner: "イ・イェジ",
        method: "判定（1-2）",
      },
      {
        weightClass: "DEEP JEWELSフライ級タイトルマッチ",
        fighterA: "中井りん",
        fighterB: "奥富夕夏",
        winner: "中井りん",
        method: "判定（5-0）",
      },
    ],
  },
  {
    slug: "rizin-52",
    org: "rizin",
    eventName: "RIZIN.52",
    date: "2026-03-07",
    venue: "有明アリーナ",
    sourceUrl: "https://jp.rizinff.com/_ct/17825885",
    fights: [
      {
        weightClass: "49.0kg契約",
        fighterA: "NOEL",
        fighterB: "イ・ボミ",
        winner: "NOEL",
        method: "ギロチンチョーク",
        round: "1R 2:07",
      },
      {
        weightClass: "57.0kg契約",
        fighterA: "新井丈",
        fighterB: "イ・ジョンヒョン",
        winner: "イ・ジョンヒョン",
        method: "TKO（左フック）",
        round: "3R 3:44",
      },
      {
        weightClass: "57.0kg契約",
        fighterA: "征矢貴",
        fighterB: "トニー・ララミー",
        winner: "トニー・ララミー",
        method: "TKO（右フック→パウンド）",
        round: "3R 2:00",
      },
      {
        weightClass: "61.0kg契約",
        fighterA: "佐藤将光",
        fighterB: "ジョン・スウィーニー",
        winner: "佐藤将光",
        method: "三角絞め",
        round: "1R 4:49",
      },
      {
        weightClass: "71.0kg契約",
        fighterA: "キム・ギョンピョ",
        fighterB: "矢地祐介",
        winner: "キム・ギョンピョ",
        method: "TKO（ドクターストップ）",
        round: "2R 4:25",
      },
      {
        weightClass: "61.0kg契約",
        fighterA: "所英男",
        fighterB: "鹿志村仁之介",
        winner: "鹿志村仁之介",
        method: "アナコンダチョーク",
        round: "1R 1:06",
      },
      {
        weightClass: "59.0kg契約",
        fighterA: "伊藤裕樹",
        fighterB: "カルロス・モタ",
        winner: "伊藤裕樹",
        method: "TKO（左ストレート→パウンド）",
        round: "1R 2:27",
      },
      {
        weightClass: "49.0kg契約",
        fighterA: "大島沙緒里",
        fighterB: "ケイト・ロータス",
        winner: "大島沙緒里",
        method: "判定（3-0）",
        round: "3R",
      },
      {
        weightClass: "71.0kg契約",
        fighterA: "ビクター・コレスニック",
        fighterB: "武田光司",
        winner: "武田光司",
        method: "判定（0-3）",
        round: "3R",
      },
      {
        weightClass: "66.0kg契約",
        fighterA: "高木凌",
        fighterB: "木村柊也",
        winner: "高木凌",
        method: "TKO（ドクターストップ：眼の負傷）",
        round: "1R 5:00",
      },
      {
        weightClass: "71.0kg契約",
        fighterA: "ルイス・グスタボ",
        fighterB: "桜庭大世",
        winner: "ルイス・グスタボ",
        method: "TKO（グラウンドパンチ）",
        round: "2R 2:32",
      },
      {
        weightClass: "66.0kg契約",
        fighterA: "秋元強真",
        fighterB: "パッチー・ミックス",
        winner: "秋元強真",
        method: "TKO（左ストレート→サッカーボールキック）",
        round: "2R 0:37",
      },
    ],
  },
  {
    slug: "rizin-53",
    org: "rizin",
    eventName: "RIZIN.53",
    date: "2026-05-10",
    venue: "GLION ARENA KOBE",
    sourceUrl: "https://jp.rizinff.com/_ct/17838643",
    fights: [
      {
        weightClass: "57.0kg契約 キックボクシング",
        fighterA: "祥汰",
        fighterB: "須藤智也",
        winner: "祥汰",
        method: "判定（3-0）",
        round: "3R",
      },
      {
        weightClass: "46.0kg契約 キックボクシング",
        fighterA: "上田樹那",
        fighterB: "北野ヒナタ",
        winner: "北野ヒナタ",
        method: "判定（0-3）",
        round: "3R",
      },
      {
        weightClass: "62.0kg契約 キックボクシング",
        fighterA: "勇志",
        fighterB: "麻太郎",
        winner: "勇志",
        method: "判定（3-0）",
        round: "3R",
      },
      {
        weightClass: "57.0kg契約 MMA特別ルール",
        fighterA: "濱口奏琉",
        fighterB: "砂田華杜",
        winner: "濱口奏琉",
        method: "TKO（パウンド）",
        round: "1R 2:33",
      },
      {
        weightClass: "66.0kg契約",
        fighterA: "中川皓貴",
        fighterB: "ジェイク・ウィルキンス",
        winner: "中川皓貴",
        method: "判定（3-0）",
        round: "3R",
      },
      {
        weightClass: "57.0kg契約",
        fighterA: "飴山聖也",
        fighterB: "平本丈",
        winner: "平本丈",
        method: "リアネイキッドチョーク",
        round: "2R 0:27",
      },
      {
        weightClass: "62.0kg契約",
        fighterA: "ジョリー",
        fighterB: "児玉兼慎",
        winner: "ジョリー",
        method: "腕ひしぎ十字固め",
        round: "1R 1:11",
      },
      {
        weightClass: "61.0kg契約",
        fighterA: "ダイキ・ライトイヤー",
        fighterB: "梅野源治",
        winner: "ダイキ・ライトイヤー",
        method: "三角絞め",
        round: "1R 2:37",
      },
      {
        weightClass: "66.0kg契約",
        fighterA: "松嶋こよみ",
        fighterB: "ライアン・カファロ",
        winner: "ライアン・カファロ",
        method: "ドラゴンスリーパー",
        round: "3R 2:23",
      },
      {
        weightClass: "71.0kg契約",
        fighterA: "宇佐美正パトリック",
        fighterB: "雑賀達也",
        winner: "宇佐美正パトリック",
        method: "KO",
        round: "1R 1:38",
      },
      {
        weightClass: "51.0kg契約",
        fighterA: "ケイト・ロータス",
        fighterB: "ケイティ・ペレス",
        winner: "ケイト・ロータス",
        method: "判定（3-0）",
        round: "3R",
      },
      {
        weightClass: "61.0kg契約",
        fighterA: "太田忍",
        fighterB: "金太郎",
        winner: "太田忍",
        method: "肩固め",
        round: "2R 4:25",
      },
      {
        weightClass: "66.0kg契約",
        fighterA: "高木凌",
        fighterB: "リー・カイウェン",
        winner: "高木凌",
        method: "TKO（右ストレート→パウンド）",
        round: "1R 1:38",
      },
      {
        weightClass: "無差別級 スタンディングバウト",
        fighterA: "平本蓮",
        fighterB: "皇治",
        winner: "引き分け",
        method: "ドロー（判定なし）",
        round: "3R",
      },
      {
        weightClass: "RIZINライト級タイトルマッチ",
        fighterA: "ルイス・グスタボ",
        fighterB: "イルホム・ノジモフ",
        winner: "ルイス・グスタボ",
        method: "TKO（レフェリーストップ）",
        round: "1R 2:08",
      },
    ],
  },
  {
    slug: "rizin-landmark-13",
    org: "rizin",
    eventName: "RIZIN LANDMARK 13",
    date: "2026-04-12",
    venue: "マリンメッセ福岡A館",
    sourceUrl: "https://jp.rizinff.com/_ct/17813447",
    fights: [
      {
        weightClass: "57.0kg契約 キックボクシング",
        fighterA: "今村流星",
        fighterB: "YU-KI",
        winner: "今村流星",
        method: "TKO（レフェリーストップ）",
        round: "2R 0:58",
      },
      {
        weightClass: "71.0kg契約 MMA特別ルール",
        fighterA: "大木良太",
        fighterB: "荒井銀二",
        winner: "大木良太",
        method: "判定（3-0）",
        round: "2R",
      },
      {
        weightClass: "61.0kg契約 MMA特別ルール",
        fighterA: "山﨑鼓大",
        fighterB: "有松朋晃",
        winner: "有松朋晃",
        method: "TKO（パウンド）",
        round: "1R 4:37",
      },
      {
        weightClass: "57.0kg契約 MMA特別ルール",
        fighterA: "八尋大輝",
        fighterB: "岡本瞬",
        winner: "岡本瞬",
        method: "判定（0-3）",
        round: "2R",
      },
      {
        weightClass: "61.0kg契約",
        fighterA: "井上聖矢",
        fighterB: "宮川日向",
        winner: "宮川日向",
        method: "判定（0-3）",
        round: "3R",
      },
      {
        weightClass: "57.0kg契約",
        fighterA: "本田良介",
        fighterB: "火の鳥",
        winner: "火の鳥",
        method: "TKO（右ストレート→パウンド）",
        round: "1R 4:59",
      },
      {
        weightClass: "71.0kg契約",
        fighterA: "ヌルハン・ズマガジー",
        fighterB: "天弥",
        winner: "ヌルハン・ズマガジー",
        method: "判定（3-0）",
        round: "3R",
      },
      {
        weightClass: "66.0kg契約",
        fighterA: "摩嶋一整",
        fighterB: "ジェームズ・ギャラガー",
        winner: "摩嶋一整",
        method: "肩固め",
        round: "3R 2:35",
      },
      {
        weightClass: "49.0kg契約",
        fighterA: "浜崎朱加",
        fighterB: "ナターシャ・クジュティナ",
        winner: "ナターシャ・クジュティナ",
        method: "腕ひしぎ十字固め",
        round: "1R 4:55",
      },
      {
        weightClass: "57.0kg契約",
        fighterA: "神龍誠",
        fighterB: "エンカジムーロ・ズールー",
        winner: "神龍誠",
        method: "アームロック",
        round: "1R 2:52",
      },
      {
        weightClass: "66.0kg契約 キックボクシング",
        fighterA: "朝久泰央",
        fighterB: "シンパヤック・ハマジム",
        winner: "朝久泰央",
        method: "KO（右ボディストレート）",
        round: "1R 1:45",
      },
      {
        weightClass: "61.0kg契約",
        fighterA: "福田龍彌",
        fighterB: "アジズベク・テミロフ",
        winner: "アジズベク・テミロフ",
        method: "KO（右フック）",
        round: "2R 1:40",
      },
      {
        weightClass: "71.0kg契約",
        fighterA: "堀江圭功",
        fighterB: "パトリッキー・ピットブル",
        winner: "堀江圭功",
        method: "判定（2-1）",
        round: "3R",
      },
      {
        weightClass: "第8代RIZINバンタム級王座決定戦",
        fighterA: "ダニー・サバテロ",
        fighterB: "後藤丈治",
        winner: "ダニー・サバテロ",
        method: "判定（3-0）",
        round: "3R",
      },
      {
        weightClass: "RIZINフェザー級タイトルマッチ",
        fighterA: "ラジャブアリ・シェイドゥラエフ",
        fighterB: "久保優太",
        winner: "ラジャブアリ・シェイドゥラエフ",
        method: "TKO（パウンド）",
        round: "1R 4:13",
      },
    ],
  },
  {
    slug: "rizin-landmark-14",
    org: "rizin",
    eventName: "RIZIN LANDMARK 14",
    date: "2026-06-06",
    venue: "ゼビオアリーナ仙台",
    sourceUrl: "https://jp.rizinff.com/_ct/17843850",
    fights: [
      {
        weightClass: "62.0kg契約 キックボクシング",
        fighterA: "岩城悠介",
        fighterB: "中泉翔",
        winner: "岩城悠介",
        method: "KO（飛び膝蹴り）",
        round: "3R 0:47",
      },
      {
        weightClass: "56.5kg契約 キックボクシング",
        fighterA: "赤平大治",
        fighterB: "内田晶",
        winner: "内田晶",
        method: "判定（0-3）",
        round: "3R",
      },
      {
        weightClass: "67.5kg契約 キックボクシング",
        fighterA: "齋藤紘也",
        fighterB: "TAaaaCHAN",
        winner: "齋藤紘也",
        method: "TKO（3ノックダウン）",
        round: "1R 1:25",
      },
      {
        weightClass: "57.0kg契約 MMA特別ルール",
        fighterA: "颯斗",
        fighterB: "湯浅帝蓮",
        winner: "颯斗",
        method: "判定（2-1）",
        round: "2R",
      },
      {
        weightClass: "61.0kg契約",
        fighterA: "井上聖矢",
        fighterB: "赤田功輝",
        winner: "井上聖矢",
        method: "KO",
        round: "3R 0:28",
      },
      {
        weightClass: "66.0kg契約",
        fighterA: "直樹",
        fighterB: "黒井海成",
        winner: "直樹",
        method: "TKO（左膝蹴り→パウンド）",
        round: "1R 3:37",
      },
      {
        weightClass: "57.0kg契約",
        fighterA: "冨澤大智",
        fighterB: "加藤瑠偉",
        winner: "冨澤大智",
        method: "TKO（グラウンドでの肘打ち）",
        round: "1R 4:37",
      },
      {
        weightClass: "71.0kg契約",
        fighterA: "矢地祐介",
        fighterB: "ISAO",
        winner: "矢地祐介",
        method: "判定（3-0）",
        round: "3R",
      },
      {
        weightClass: "71.1kg契約",
        fighterA: "ベイノア",
        fighterB: "芳賀ビラル海",
        winner: "ベイノア",
        method: "KO（左ハイキック）",
        round: "2R 0:10",
      },
      {
        weightClass: "121.2kg契約",
        fighterA: "酒井リョウ",
        fighterB: "貴賢神",
        winner: "貴賢神",
        method: "TKO（右ストレート→パウンド）",
        round: "1R 1:16",
      },
      {
        weightClass: "59.0kg契約",
        fighterA: "元谷友貴",
        fighterB: "トニー・ララミー",
        winner: "トニー・ララミー",
        method: "判定（0-3）",
        round: "3R",
      },
      {
        weightClass: "RIZINフライ級タイトルマッチ",
        fighterA: "扇久保博正",
        fighterB: "神龍誠",
        winner: "神龍誠",
        method: "判定（0-3）",
        round: "3R",
      },
    ],
  },
];

export function getEventResult(slug: string): EventResult | undefined {
  return EVENT_RESULTS.find((e) => e.slug === slug);
}
