import { SourceKey } from "./sources";

export interface FightRecord {
  date: string;
  opponent: string;
  result: "win" | "loss" | "draw";
  method: string;
  event: string;
  round: string;
}

export interface Fighter {
  slug: string;
  nameJa: string;
  nameEn: string;
  org: SourceKey;
  weightClass: string;
  wins: number;
  losses: number;
  draws: number;
  ko: number;
  sub: number;
  decision: number;
  history: FightRecord[];
  // English Wikipedia article title with a "{{MMA record start}}" table.
  // Only set when one is known to exist; omitted fighters keep seed data.
  wikiTitleEn?: string;
  // jp.ufc.com/athlete/<slug> — UFC所属選手のみ。ニックネームをWikipediaより
  // 優先してUFC公式プロフィールから取得するために使う。
  ufcSlug?: string;
  // 日本語版WikipediaのFight-cont戦績データを使う場合のページ名。
  wikiTitleJa?: string;
  // 通称（ニックネーム）を表示しない選手向けフラグ。
  noNickname?: boolean;
  // 通称を固定値で指定する場合に使う。設定時はUFC公式/Wikipediaからの
  // 自動取得より優先される（noNicknameより後で判定）。
  nickname?: string;
}

// Seed data. Per mnews-spec.md this is normally synced from the Wikipedia API.
export const FIGHTERS: Fighter[] = [
  {
    slug: "taira-tatsuro",
    nameJa: "平良 達郎",
    nameEn: "Tatsuro Taira",
    org: "ufc",
    weightClass: "フライ級",
    wins: 18,
    losses: 1,
    draws: 0,
    ko: 3,
    sub: 14,
    decision: 1,
    history: [
      { date: "2026-02-01", opponent: "Joshua Van", result: "win", method: "submission (rear-naked choke)", event: "UFC 327", round: "R3" },
      { date: "2025-09-13", opponent: "Carlos Hernandez", result: "win", method: "decision", event: "UFC 319", round: "R3" },
      { date: "2025-04-12", opponent: "Brandon Royval", result: "win", method: "decision", event: "UFC 314", round: "R5" },
    ],
    wikiTitleEn: "Tatsuro Taira",
    ufcSlug: "tatsuro-taira",
    nickname: "The Best",
  },
  {
    slug: "nakamura-rinya",
    nameJa: "中村 倫也",
    nameEn: "Rinya Nakamura",
    org: "ufc",
    weightClass: "バンタム級",
    wins: 10,
    losses: 1,
    draws: 0,
    ko: 2,
    sub: 6,
    decision: 2,
    history: [
      { date: "2025-12-07", opponent: "Cody Gibson", result: "win", method: "submission", event: "UFC Fight Night", round: "R2" },
    ],
    wikiTitleEn: "Rinya Nakamura",
    ufcSlug: "rinya-nakamura",
    nickname: "Hybrid",
  },
  {
    slug: "horiguchi-kyoji",
    nameJa: "堀口 恭司",
    nameEn: "Kyoji Horiguchi",
    org: "ufc",
    weightClass: "フライ級",
    wins: 30,
    losses: 5,
    draws: 0,
    ko: 18,
    sub: 6,
    decision: 6,
    history: [
      { date: "2025-12-31", opponent: "Yuki Motoya", result: "win", method: "KO", event: "RIZIN LANDMARK 12", round: "R1" },
    ],
    wikiTitleEn: "Kyoji Horiguchi",
    ufcSlug: "kyoji-horiguchi",
    nickname: "KARATE KID",
  },
  {
    slug: "asakura-kai",
    nameJa: "朝倉 海",
    nameEn: "Kai Asakura",
    org: "ufc",
    weightClass: "バンタム級",
    wins: 18,
    losses: 4,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Kai Asakura",
    ufcSlug: "kai-asakura",
    nickname: "革命のアウトサイダー",
  },
  {
    slug: "tsuruya-rei",
    nameJa: "鶴屋 怜",
    nameEn: "Rei Tsuruya",
    org: "ufc",
    weightClass: "フライ級",
    wins: 11,
    losses: 1,
    draws: 0,
    ko: 4,
    sub: 5,
    decision: 2,
    history: [],
    noNickname: true,
  },
  {
    slug: "hiramoto-ren",
    nameJa: "平本 蓮",
    nameEn: "Ren Hiramoto",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 14,
    losses: 4,
    draws: 0,
    ko: 7,
    sub: 3,
    decision: 4,
    history: [],
    wikiTitleEn: "Ren Hiramoto",
    nickname: "令和の黒きカリスマ",
  },
  {
    slug: "asakura-mikuru",
    nameJa: "朝倉 未来",
    nameEn: "Mikuru Asakura",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 19,
    losses: 5,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Mikuru Asakura",
    nickname: "路上の伝説",
  },
  {
    slug: "koike-kleber",
    nameJa: "クレベル コイケ エルベスト",
    nameEn: "Kleber Koike Erbst",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 30,
    losses: 9,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Kleber Koike Erbst",
    nickname: "柔術界の鬼神",
  },
  {
    slug: "akimoto-kyoma",
    nameJa: "秋元 強真",
    nameEn: "Kyoma Akimoto",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 12,
    losses: 1,
    draws: 0,
    ko: 7,
    sub: 2,
    decision: 3,
    history: [],
    // 英語版Wikipediaに記事がまだ無いため戦績はシードデータのまま。
    nickname: "超強真星",
  },
  {
    slug: "inoue-naoki",
    nameJa: "井上 直樹",
    nameEn: "Naoki Inoue",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 19,
    losses: 3,
    draws: 0,
    ko: 5,
    sub: 6,
    decision: 8,
    history: [],
    wikiTitleEn: "Naoki Inoue",
    nickname: "地獄のエンジェル",
  },
  {
    slug: "izawa-seika",
    nameJa: "伊澤 星花",
    nameEn: "Seika Izawa",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 19,
    losses: 0,
    draws: 0,
    ko: 4,
    sub: 10,
    decision: 5,
    history: [],
    wikiTitleEn: "Seika Izawa",
    nickname: "天然技巧派 IQファイター",
  },
  {
    slug: "rena",
    nameJa: "RENA",
    nameEn: "Rena Kubota",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 15,
    losses: 6,
    draws: 0,
    ko: 8,
    sub: 2,
    decision: 5,
    history: [],
    wikiTitleEn: "Rena Kubota",
    wikiTitleJa: "RENA (格闘家)",
    nickname: "NIPPONのツヨカワ女王",
  },
  {
    slug: "saito-yutaka",
    nameJa: "斎藤 裕",
    nameEn: "Yutaka Saito",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 21,
    losses: 9,
    draws: 2,
    ko: 5,
    sub: 2,
    decision: 14,
    history: [],
    // 英語版Wikipediaに記事がまだ無いため戦績はシードデータのまま。
    nickname: "令和の修斗伝承者",
  },
  {
    slug: "ya-man",
    nameJa: "YA-MAN",
    nameEn: "YA-MAN",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 11,
    losses: 6,
    draws: 0,
    ko: 4,
    sub: 2,
    decision: 5,
    history: [],
    wikiTitleEn: "YA-MAN",
    nickname: "King of Street Fight",
  },
  {
    slug: "hagiwara-kyohei",
    nameJa: "萩原 京平",
    nameEn: "Kyohei Hagiwara",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 9,
    losses: 11,
    draws: 0,
    ko: 7,
    sub: 0,
    decision: 2,
    history: [],
    // 英語版Wikipediaに記事がまだ無いため戦績はシードデータ（日本語版より）。
    nickname: "反逆のSMOKER",
  },
  {
    slug: "majima-kazumasa",
    nameJa: "摩嶋 一整",
    nameEn: "Kazumasa Majima",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 19,
    losses: 6,
    draws: 0,
    ko: 1,
    sub: 16,
    decision: 2,
    history: [],
    nickname: "町工場のグラップラー",
  },
  {
    slug: "hiroya",
    nameJa: "ヒロヤ",
    nameEn: "Hiroya",
    org: "rizin",
    weightClass: "フライ級",
    wins: 11,
    losses: 15,
    draws: 1,
    ko: 4,
    sub: 3,
    decision: 3,
    history: [],
    // 英語版Wikipediaに記事はあるが戦績テーブルが無いためシードデータ。
    nickname: "不屈のヤングガン",
  },
  {
    slug: "shinryu-makoto",
    nameJa: "神龍 誠",
    nameEn: "Makoto Takahashi",
    org: "rizin",
    weightClass: "フライ級",
    wins: 23,
    losses: 5,
    draws: 1,
    ko: 0,
    sub: 7,
    decision: 16,
    history: [],
    wikiTitleEn: "Makoto Takahashi (fighter)",
    nickname: "日本のラフ・ダイヤモンド",
  },
  {
    slug: "ougikubo-hiromasa",
    nameJa: "扇久保 博正",
    nameEn: "Hiromasa Ougikubo",
    org: "rizin",
    weightClass: "フライ級",
    wins: 30,
    losses: 9,
    draws: 2,
    ko: 1,
    sub: 6,
    decision: 23,
    history: [],
    wikiTitleJa: "扇久保博正",
    nickname: "打・投・極・根性",
  },
  {
    slug: "motoya-yuki",
    nameJa: "元谷 友貴",
    nameEn: "Yuki Motoya",
    org: "rizin",
    weightClass: "フライ級",
    wins: 39,
    losses: 14,
    draws: 0,
    ko: 8,
    sub: 14,
    decision: 17,
    history: [],
    nickname: "DEEPのファンタジスタ",
  },
  {
    slug: "yachi-yusuke",
    nameJa: "矢地 祐介",
    nameEn: "Yusuke Yachi",
    org: "rizin",
    weightClass: "ライト級",
    wins: 29,
    losses: 16,
    draws: 0,
    ko: 6,
    sub: 5,
    decision: 18,
    history: [],
    // 英語版Wikipediaに記事はあるが戦績テーブルが無いためシードデータ。
    nickname: "お祭り漢",
  },
  {
    slug: "shinotsuka-tatsuki",
    nameJa: "篠塚 辰樹",
    nameEn: "Tatsuki Shinotsuka",
    org: "rizin",
    weightClass: "フライ級",
    wins: 1,
    losses: 1,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Tatsuki Shinotsuka",
    nickname: "THE PROBLEM BOY",
  },
  {
    slug: "tomizawa-daichi",
    nameJa: "冨澤 大智",
    nameEn: "Daichi Tomizawa",
    org: "rizin",
    weightClass: "フライ級",
    wins: 3,
    losses: 2,
    draws: 0,
    ko: 2,
    sub: 0,
    decision: 1,
    history: [],
    nickname: "BDの闘神",
  },
  {
    slug: "ashizawa-ryusei",
    nameJa: "芦澤 竜誠",
    nameEn: "Ryusei Ashizawa",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 2,
    losses: 4,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Ryusei Ashizawa",
    nickname: "BAD NAMAZU",
  },
  {
    slug: "jolly",
    nameJa: "ジョリー",
    nameEn: "Jolly",
    org: "rizin",
    weightClass: "フライ級",
    wins: 4,
    losses: 0,
    draws: 0,
    ko: 2,
    sub: 2,
    decision: 0,
    history: [],
    nickname: "危険な金獅子",
  },
  {
    slug: "fukuda-ryuya",
    nameJa: "福田 龍彌",
    nameEn: "Ryuya Fukuda",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 26,
    losses: 10,
    draws: 1,
    ko: 13,
    sub: 1,
    decision: 12,
    history: [],
    nickname: "壬生の大蛇",
  },
  {
    slug: "takagi-ryo",
    nameJa: "高木 凌",
    nameEn: "Ryo Takagi",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 11,
    losses: 3,
    draws: 0,
    ko: 8,
    sub: 1,
    decision: 2,
    history: [],
    nickname: "ゴールデン・ライト",
  },
  {
    slug: "ota-shinobu",
    nameJa: "太田 忍",
    nameEn: "Shinobu Ota",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 8,
    losses: 5,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Shinobu Ota",
    nickname: "銀の忍者レスラー",
  },
  {
    slug: "kate-lotus",
    nameJa: "ケイト・ロータス",
    nameEn: "Kate Lotus",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 10,
    losses: 8,
    draws: 0,
    ko: 2,
    sub: 2,
    decision: 6,
    history: [],
    nickname: "不屈の睡蓮",
  },
  {
    slug: "hiramoto-jo",
    nameJa: "平本 丈",
    nameEn: "Jo Hiramoto",
    org: "rizin",
    weightClass: "フライ級",
    wins: 3,
    losses: 2,
    draws: 0,
    ko: 0,
    sub: 1,
    decision: 2,
    history: [],
    nickname: "美しき金狼",
  },
  {
    slug: "oshima-saori",
    nameJa: "大島 沙緒里",
    nameEn: "Saori Oshima",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 16,
    losses: 7,
    draws: 0,
    ko: 2,
    sub: 9,
    decision: 5,
    history: [],
    wikiTitleEn: "Saori Oshima",
    nickname: "極めのミクロクイーン",
  },
  {
    slug: "kashimura-ninnosuke",
    nameJa: "鹿志村 仁之介",
    nameEn: "Ninnosuke Kashimura",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 12,
    losses: 5,
    draws: 0,
    ko: 1,
    sub: 10,
    decision: 1,
    history: [],
    nickname: "黒帯のリベリオン",
  },
  {
    slug: "sato-masamitsu",
    nameJa: "佐藤 将光",
    nameEn: "Masamitsu Sato",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 38,
    losses: 17,
    draws: 2,
    ko: 20,
    sub: 4,
    decision: 14,
    history: [],
    nickname: "ミスターいぶし銀",
  },
  {
    slug: "goto-joji",
    nameJa: "後藤 丈治",
    nameEn: "Joji Goto",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 19,
    losses: 9,
    draws: 0,
    ko: 9,
    sub: 4,
    decision: 6,
    history: [],
    nickname: "北海の宮本武蔵",
  },
  {
    slug: "ito-yuki",
    nameJa: "伊藤 裕樹",
    nameEn: "Yuki Ito",
    org: "rizin",
    weightClass: "フライ級",
    wins: 20,
    losses: 7,
    draws: 0,
    ko: 9,
    sub: 2,
    decision: 9,
    history: [],
    nickname: "ザ・ギャンブラー",
  },
  {
    slug: "suzuki-chihiro",
    nameJa: "鈴木 千裕",
    nameEn: "Chihiro Suzuki",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 13,
    losses: 6,
    draws: 0,
    ko: 7,
    sub: 1,
    decision: 5,
    history: [],
    wikiTitleEn: "Chihiro Suzuki (fighter)",
    nickname: "天下無双の稲妻ボーイ",
  },
  {
    slug: "seiya-takashi",
    nameJa: "征矢 貴",
    nameEn: "Takashi Seiya",
    org: "rizin",
    weightClass: "フライ級",
    wins: 13,
    losses: 8,
    draws: 1,
    ko: 9,
    sub: 0,
    decision: 4,
    history: [],
    nickname: "松戸の鴉松戸の不死鳥",
  },
  {
    slug: "noel",
    nameJa: "NOEL",
    nameEn: "NOEL",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 4,
    losses: 2,
    draws: 0,
    ko: 0,
    sub: 4,
    decision: 0,
    history: [],
    noNickname: true,
  },
  {
    slug: "nomura-shunta",
    nameJa: "野村 駿太",
    nameEn: "Shunta Nomura",
    org: "rizin",
    weightClass: "ライト級",
    wins: 10,
    losses: 2,
    draws: 0,
    ko: 4,
    sub: 0,
    decision: 6,
    history: [],
    nickname: "駿速のKARATEヘラクレス",
  },
  {
    slug: "yamamoto-arsen",
    nameJa: "山本 アーセン",
    nameEn: "Arsen Yamamoto",
    org: "rizin",
    weightClass: "フライ級",
    wins: 6,
    losses: 8,
    draws: 0,
    ko: 2,
    sub: 1,
    decision: 3,
    history: [],
    nickname: "格闘一家の最強DNA",
  },
  {
    slug: "horie-keiko",
    nameJa: "堀江 圭功",
    nameEn: "Keikou Horie",
    org: "rizin",
    weightClass: "ライト級",
    wins: 15,
    losses: 6,
    draws: 0,
    ko: 7,
    sub: 0,
    decision: 8,
    history: [],
    nickname: "裸の銃をもつ漢",
  },
  {
    slug: "souza-roberto-satoshi",
    nameJa: "ホベルト・サトシ・ソウザ",
    nameEn: "Roberto Satoshi Souza",
    org: "rizin",
    weightClass: "ライト級",
    wins: 20,
    losses: 4,
    draws: 0,
    ko: 6,
    sub: 13,
    decision: 1,
    history: [],
    wikiTitleEn: "Roberto de Souza",
    nickname: "カナリア色の大和魂",
  },
  {
    slug: "ando-tatsuya",
    nameJa: "安藤 達也",
    nameEn: "Tatsuya Ando",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 16,
    losses: 5,
    draws: 1,
    ko: 7,
    sub: 6,
    decision: 3,
    history: [],
    nickname: "遅れてきた\"怪物\"",
  },
  {
    slug: "sakuraba-taisei",
    nameJa: "桜庭 大世",
    nameEn: "Taisei Sakuraba",
    org: "rizin",
    weightClass: "ライト級",
    wins: 2,
    losses: 2,
    draws: 0,
    ko: 1,
    sub: 1,
    decision: 0,
    history: [],
    nickname: "Saku Jr.",
  },
  {
    slug: "usami-sho-patrick",
    nameJa: "宇佐美正パトリック",
    nameEn: "Patrick Usami",
    org: "rizin",
    weightClass: "ライト級",
    wins: 9,
    losses: 5,
    draws: 0,
    ko: 7,
    sub: 0,
    decision: 2,
    history: [],
    nickname: "聖なる破壊者",
  },
  {
    slug: "umeno-genji",
    nameJa: "梅野 源治",
    nameEn: "Genji Umeno",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 2,
    losses: 0,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 2,
    history: [],
    wikiTitleEn: "Genji Umeno",
    nickname: "ヤバいだろ",
  },
  {
    slug: "kintaro",
    nameJa: "金太郎",
    nameEn: "Kintaro",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 16,
    losses: 15,
    draws: 2,
    ko: 9,
    sub: 3,
    decision: 4,
    history: [],
    nickname: "マサカリ殺法",
  },
  {
    slug: "suda-moeri",
    nameJa: "須田 萌里",
    nameEn: "Moeri Suda",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 15,
    losses: 7,
    draws: 0,
    ko: 0,
    sub: 10,
    decision: 5,
    history: [],
    wikiTitleEn: "Moeri Suda",
    nickname: "寝技の萌ちゃん",
  },
  {
    slug: "kubo-yuta",
    nameJa: "久保 優太",
    nameEn: "Yuta Kubo",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 5,
    losses: 3,
    draws: 0,
    ko: 2,
    sub: 1,
    decision: 2,
    history: [],
    wikiTitleEn: "Yuta Kubo",
    nickname: "微笑みスナイパー",
  },
  {
    slug: "takeda-koji",
    nameJa: "武田 光司",
    nameEn: "Koji Takeda",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 19,
    losses: 8,
    draws: 0,
    ko: 2,
    sub: 6,
    decision: 11,
    history: [],
    nickname: "漆黒のヘラクレス",
  },
];

export function getFighter(slug: string): Fighter | undefined {
  return FIGHTERS.find((f) => f.slug === slug);
}

export interface FighterRates {
  winRate: number | null; // 勝率（%） wins / (wins+losses+draws)
  finishRate: number | null; // フィニッシュ率（%） (KO+一本) / wins
}

export function calcFighterRates(f: Pick<Fighter, "wins" | "losses" | "draws" | "ko" | "sub">): FighterRates {
  const total = f.wins + f.losses + f.draws;
  const winRate = total > 0 ? Math.round((f.wins / total) * 100) : null;
  const finishRate = f.wins > 0 ? Math.round(((f.ko + f.sub) / f.wins) * 100) : null;
  return { winRate, finishRate };
}
