import { SourceKey } from "./sources";

export interface FightRecord {
  date: string;
  opponent: string;
  result: "win" | "loss" | "draw";
  method: string;
  event: string;
  round: string;
}

export interface Fighter {
  slug: string;
  nameJa: string;
  nameEn: string;
  org: SourceKey;
  weightClass: string;
  wins: number;
  losses: number;
  draws: number;
  ko: number;
  sub: number;
  decision: number;
  history: FightRecord[];
  // English Wikipedia article title with a "{{MMA record start}}" table.
  // Only set when one is known to exist; omitted fighters keep seed data.
  wikiTitleEn?: string;
  // jp.ufc.com/athlete/<slug> — UFC所属選手のみ。ニックネームをWikipediaより
  // 優先してUFC公式プロフィールから取得するために使う。
  ufcSlug?: string;
  // 日本語版WikipediaのFight-cont戦績データを使う場合のページ名。
  wikiTitleJa?: string;
  // 通称（ニックネーム）を表示しない選手向けフラグ。
  noNickname?: boolean;
  // 通称を固定値で指定する場合に使う。設定時はUFC公式/Wikipediaからの
  // 自動取得より優先される（noNicknameより後で判定）。
  nickname?: string;
}

// Seed data. Per mnews-spec.md this is normally synced from the Wikipedia API.
export const FIGHTERS: Fighter[] = [
  {
    slug: "taira-tatsuro",
    nameJa: "平良 達郎",
    nameEn: "Tatsuro Taira",
    org: "ufc",
    weightClass: "フライ級",
    wins: 18,
    losses: 1,
    draws: 0,
    ko: 3,
    sub: 14,
    decision: 1,
    history: [
      { date: "2026-02-01", opponent: "Joshua Van", result: "win", method: "submission (rear-naked choke)", event: "UFC 327", round: "R3" },
      { date: "2025-09-13", opponent: "Carlos Hernandez", result: "win", method: "decision", event: "UFC 319", round: "R3" },
      { date: "2025-04-12", opponent: "Brandon Royval", result: "win", method: "decision", event: "UFC 314", round: "R5" },
    ],
    wikiTitleEn: "Tatsuro Taira",
    ufcSlug: "tatsuro-taira",
    nickname: "The Best",
  },
  {
    slug: "nakamura-rinya",
    nameJa: "中村 倫也",
    nameEn: "Rinya Nakamura",
    org: "ufc",
    weightClass: "バンタム級",
    wins: 10,
    losses: 1,
    draws: 0,
    ko: 2,
    sub: 6,
    decision: 2,
    history: [
      { date: "2025-12-07", opponent: "Cody Gibson", result: "win", method: "submission", event: "UFC Fight Night", round: "R2" },
    ],
    wikiTitleEn: "Rinya Nakamura",
    wikiTitleJa: "中村倫也 (格闘家)",
    ufcSlug: "rinya-nakamura",
    nickname: "Hybrid",
  },
  {
    slug: "horiguchi-kyoji",
    nameJa: "堀口 恭司",
    nameEn: "Kyoji Horiguchi",
    org: "ufc",
    weightClass: "フライ級",
    wins: 30,
    losses: 5,
    draws: 0,
    ko: 18,
    sub: 6,
    decision: 6,
    history: [
      { date: "2025-12-31", opponent: "Yuki Motoya", result: "win", method: "KO", event: "RIZIN LANDMARK 12", round: "R1" },
    ],
    wikiTitleEn: "Kyoji Horiguchi",
    ufcSlug: "kyoji-horiguchi",
    nickname: "KARATE KID",
  },
  {
    slug: "asakura-kai",
    nameJa: "朝倉 海",
    nameEn: "Kai Asakura",
    org: "ufc",
    weightClass: "バンタム級",
    wins: 18,
    losses: 4,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Kai Asakura",
    ufcSlug: "kai-asakura",
    nickname: "革命のアウトサイダー",
  },
  {
    slug: "tsuruya-rei",
    nameJa: "鶴屋 怜",
    nameEn: "Rei Tsuruya",
    org: "ufc",
    weightClass: "フライ級",
    wins: 11,
    losses: 1,
    draws: 0,
    ko: 4,
    sub: 5,
    decision: 2,
    history: [],
    noNickname: true,
  },
  {
    slug: "hiramoto-ren",
    nameJa: "平本 蓮",
    nameEn: "Ren Hiramoto",
    org: "rizin",
    weightClass: "フェザー級",
    // MMA戦績のみ(キックボクシング戦績を混在させない)
    wins: 4,
    losses: 3,
    draws: 0,
    ko: 1,
    sub: 0,
    decision: 3,
    history: [],
    wikiTitleEn: "Ren Hiramoto",
    nickname: "令和の黒きカリスマ",
  },
  {
    slug: "asakura-mikuru",
    nameJa: "朝倉 未来",
    nameEn: "Mikuru Asakura",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 19,
    losses: 5,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Mikuru Asakura",
    nickname: "路上の伝説",
  },
  {
    slug: "koike-kleber",
    nameJa: "クレベル・コイケ",
    nameEn: "Kleber Koike",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 30,
    losses: 9,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Kleber Koike Erbst",
    wikiTitleJa: "クレベル・コイケ",
    nickname: "柔術界の鬼神",
  },
  {
    slug: "akimoto-kyoma",
    nameJa: "秋元 強真",
    nameEn: "Kyoma Akimoto",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 12,
    losses: 1,
    draws: 0,
    ko: 7,
    sub: 2,
    decision: 3,
    history: [],
    // 英語版Wikipediaに記事がまだ無いため戦績はシードデータのまま。
    nickname: "超強真星",
  },
  {
    slug: "inoue-naoki",
    nameJa: "井上 直樹",
    nameEn: "Naoki Inoue",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 19,
    losses: 3,
    draws: 0,
    ko: 5,
    sub: 6,
    decision: 8,
    history: [],
    wikiTitleEn: "Naoki Inoue",
    wikiTitleJa: "井上直樹 (格闘家)",
    nickname: "地獄のエンジェル",
  },
  {
    slug: "izawa-seika",
    nameJa: "伊澤 星花",
    nameEn: "Seika Izawa",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 19,
    losses: 0,
    draws: 0,
    ko: 4,
    sub: 10,
    decision: 5,
    history: [],
    wikiTitleEn: "Seika Izawa",
    nickname: "天然技巧派 IQファイター",
  },
  {
    slug: "rena",
    nameJa: "RENA",
    nameEn: "Rena Kubota",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 15,
    losses: 6,
    draws: 0,
    ko: 8,
    sub: 2,
    decision: 5,
    history: [],
    wikiTitleEn: "Rena Kubota",
    wikiTitleJa: "RENA (格闘家)",
    nickname: "NIPPONのツヨカワ女王",
  },
  {
    slug: "saito-yutaka",
    nameJa: "斎藤 裕",
    nameEn: "Yutaka Saito",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 21,
    losses: 9,
    draws: 2,
    ko: 5,
    sub: 2,
    decision: 14,
    history: [],
    // 英語版Wikipediaに記事がまだ無いため戦績はシードデータのまま。
    nickname: "令和の修斗伝承者",
    wikiTitleJa: "斎藤裕 (格闘家)",
  },
  {
    slug: "ya-man",
    nameJa: "YA-MAN",
    nameEn: "YA-MAN",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 11,
    losses: 6,
    draws: 0,
    ko: 4,
    sub: 2,
    decision: 5,
    history: [],
    wikiTitleEn: "YA-MAN",
    nickname: "King of Street Fight",
  },
  {
    slug: "hagiwara-kyohei",
    nameJa: "萩原 京平",
    nameEn: "Kyohei Hagiwara",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 9,
    losses: 11,
    draws: 0,
    ko: 7,
    sub: 0,
    decision: 2,
    history: [],
    // 英語版Wikipediaに記事がまだ無いため戦績はシードデータ（日本語版より）。
    nickname: "反逆のSMOKER",
  },
  {
    slug: "majima-kazumasa",
    nameJa: "摩嶋 一整",
    nameEn: "Kazumasa Majima",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 19,
    losses: 6,
    draws: 0,
    ko: 1,
    sub: 16,
    decision: 2,
    history: [],
    nickname: "町工場のグラップラー",
  },
  {
    slug: "hiroya",
    nameJa: "ヒロヤ",
    nameEn: "Hiroya",
    org: "rizin",
    weightClass: "フライ級",
    wins: 11,
    losses: 15,
    draws: 1,
    ko: 4,
    sub: 3,
    decision: 3,
    history: [],
    // 英語版Wikipediaに記事はあるが戦績テーブルが無いためシードデータ。
    nickname: "不屈のヤングガン",
  },
  {
    slug: "shinryu-makoto",
    nameJa: "神龍 誠",
    nameEn: "Makoto Takahashi",
    org: "rizin",
    weightClass: "フライ級",
    wins: 23,
    losses: 5,
    draws: 1,
    ko: 0,
    sub: 7,
    decision: 16,
    history: [],
    wikiTitleEn: "Makoto Takahashi (fighter)",
    nickname: "日本のラフ・ダイヤモンド",
  },
  {
    slug: "ougikubo-hiromasa",
    nameJa: "扇久保 博正",
    nameEn: "Hiromasa Ougikubo",
    org: "rizin",
    weightClass: "フライ級",
    wins: 30,
    losses: 9,
    draws: 2,
    ko: 1,
    sub: 6,
    decision: 23,
    history: [],
    wikiTitleJa: "扇久保博正",
    nickname: "打・投・極・根性",
  },
  {
    slug: "motoya-yuki",
    nameJa: "元谷 友貴",
    nameEn: "Yuki Motoya",
    org: "rizin",
    weightClass: "フライ級",
    wins: 39,
    losses: 14,
    draws: 0,
    ko: 8,
    sub: 14,
    decision: 17,
    history: [],
    nickname: "DEEPのファンタジスタ",
  },
  {
    slug: "yachi-yusuke",
    nameJa: "矢地 祐介",
    nameEn: "Yusuke Yachi",
    org: "rizin",
    weightClass: "ライト級",
    wins: 29,
    losses: 16,
    draws: 0,
    ko: 6,
    sub: 5,
    decision: 18,
    history: [],
    // 英語版Wikipediaに記事はあるが戦績テーブルが無いためシードデータ。
    nickname: "お祭り漢",
  },
  {
    slug: "shinotsuka-tatsuki",
    nameJa: "篠塚 辰樹",
    nameEn: "Tatsuki Shinotsuka",
    org: "rizin",
    weightClass: "フライ級",
    wins: 1,
    losses: 1,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Tatsuki Shinotsuka",
    nickname: "THE PROBLEM BOY",
  },
  {
    slug: "tomizawa-daichi",
    nameJa: "冨澤 大智",
    nameEn: "Daichi Tomizawa",
    org: "rizin",
    weightClass: "フライ級",
    wins: 3,
    losses: 2,
    draws: 0,
    ko: 2,
    sub: 0,
    decision: 1,
    history: [],
    nickname: "BDの闘神",
  },
  {
    slug: "ashizawa-ryusei",
    nameJa: "芦澤 竜誠",
    nameEn: "Ryusei Ashizawa",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 2,
    losses: 4,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Ryusei Ashizawa",
    nickname: "BAD NAMAZU",
  },
  {
    slug: "jolly",
    nameJa: "ジョリー",
    nameEn: "Jolly",
    org: "rizin",
    weightClass: "フライ級",
    wins: 4,
    losses: 0,
    draws: 0,
    ko: 2,
    sub: 2,
    decision: 0,
    history: [],
    nickname: "危険な金獅子",
    wikiTitleJa: "ジョリー (格闘家)",
  },
  {
    slug: "fukuda-ryuya",
    nameJa: "福田 龍彌",
    nameEn: "Ryuya Fukuda",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 26,
    losses: 10,
    draws: 1,
    ko: 13,
    sub: 1,
    decision: 12,
    history: [],
    nickname: "壬生の大蛇",
  },
  {
    slug: "takagi-ryo",
    nameJa: "高木 凌",
    nameEn: "Ryo Takagi",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 11,
    losses: 3,
    draws: 0,
    ko: 8,
    sub: 1,
    decision: 2,
    history: [],
    nickname: "ゴールデン・ライト",
  },
  {
    slug: "ota-shinobu",
    nameJa: "太田 忍",
    nameEn: "Shinobu Ota",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 8,
    losses: 5,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleEn: "Shinobu Ota",
    nickname: "銀の忍者レスラー",
  },
  {
    slug: "kate-lotus",
    nameJa: "ケイト・ロータス",
    nameEn: "Kate Lotus",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 10,
    losses: 8,
    draws: 0,
    ko: 2,
    sub: 2,
    decision: 6,
    history: [],
    nickname: "不屈の睡蓮",
  },
  {
    slug: "hiramoto-jo",
    nameJa: "平本 丈",
    nameEn: "Jo Hiramoto",
    org: "rizin",
    weightClass: "フライ級",
    wins: 3,
    losses: 2,
    draws: 0,
    ko: 0,
    sub: 1,
    decision: 2,
    history: [],
    nickname: "美しき金狼",
  },
  {
    slug: "oshima-saori",
    nameJa: "大島 沙緒里",
    nameEn: "Saori Oshima",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 16,
    losses: 7,
    draws: 0,
    ko: 2,
    sub: 9,
    decision: 5,
    history: [],
    wikiTitleEn: "Saori Oshima",
    nickname: "極めのミクロクイーン",
  },
  {
    slug: "kashimura-ninnosuke",
    nameJa: "鹿志村 仁之介",
    nameEn: "Ninnosuke Kashimura",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 12,
    losses: 5,
    draws: 0,
    ko: 1,
    sub: 10,
    decision: 1,
    history: [],
    nickname: "黒帯のリベリオン",
  },
  {
    slug: "sato-masamitsu",
    nameJa: "佐藤 将光",
    nameEn: "Masamitsu Sato",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 38,
    losses: 17,
    draws: 2,
    ko: 20,
    sub: 4,
    decision: 14,
    history: [],
    nickname: "ミスターいぶし銀",
  },
  {
    slug: "goto-joji",
    nameJa: "後藤 丈治",
    nameEn: "Joji Goto",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 19,
    losses: 9,
    draws: 0,
    ko: 9,
    sub: 4,
    decision: 6,
    history: [],
    nickname: "北海の宮本武蔵",
  },
  {
    slug: "ito-yuki",
    nameJa: "伊藤 裕樹",
    nameEn: "Yuki Ito",
    org: "rizin",
    weightClass: "フライ級",
    wins: 20,
    losses: 7,
    draws: 0,
    ko: 9,
    sub: 2,
    decision: 9,
    history: [],
    nickname: "ザ・ギャンブラー",
    wikiTitleJa: "伊藤裕樹 (格闘家)",
  },
  {
    slug: "suzuki-chihiro",
    nameJa: "鈴木 千裕",
    nameEn: "Chihiro Suzuki",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 13,
    losses: 6,
    draws: 0,
    ko: 7,
    sub: 1,
    decision: 5,
    history: [],
    wikiTitleEn: "Chihiro Suzuki (fighter)",
    nickname: "天下無双の稲妻ボーイ",
  },
  {
    slug: "seiya-takashi",
    nameJa: "征矢 貴",
    nameEn: "Takashi Seiya",
    org: "rizin",
    weightClass: "フライ級",
    wins: 13,
    losses: 8,
    draws: 1,
    ko: 9,
    sub: 0,
    decision: 4,
    history: [],
    nickname: "松戸の不死鳥",
  },
  {
    slug: "noel",
    nameJa: "NOEL",
    nameEn: "NOEL",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 4,
    losses: 2,
    draws: 0,
    ko: 0,
    sub: 4,
    decision: 0,
    history: [],
    noNickname: true,
    wikiTitleJa: "NOEL (格闘家)",
  },
  {
    slug: "nomura-shunta",
    nameJa: "野村 駿太",
    nameEn: "Shunta Nomura",
    org: "rizin",
    weightClass: "ライト級",
    wins: 10,
    losses: 2,
    draws: 0,
    ko: 4,
    sub: 0,
    decision: 6,
    history: [],
    nickname: "駿速のKARATEヘラクレス",
  },
  {
    slug: "yamamoto-arsen",
    nameJa: "山本 アーセン",
    nameEn: "Arsen Yamamoto",
    org: "rizin",
    weightClass: "フライ級",
    wins: 6,
    losses: 8,
    draws: 0,
    ko: 2,
    sub: 1,
    decision: 3,
    history: [],
    nickname: "格闘一家の最強DNA",
  },
  {
    slug: "horie-keiko",
    nameJa: "堀江 圭功",
    nameEn: "Keikou Horie",
    org: "rizin",
    weightClass: "ライト級",
    wins: 15,
    losses: 6,
    draws: 0,
    ko: 7,
    sub: 0,
    decision: 8,
    history: [],
    nickname: "裸の銃をもつ漢",
  },
  {
    slug: "souza-roberto-satoshi",
    nameJa: "ホベルト・サトシ・ソウザ",
    nameEn: "Roberto Satoshi Souza",
    org: "rizin",
    weightClass: "ライト級",
    wins: 20,
    losses: 4,
    draws: 0,
    ko: 6,
    sub: 13,
    decision: 1,
    history: [],
    wikiTitleEn: "Roberto de Souza",
    nickname: "カナリア色の大和魂",
  },
  {
    slug: "ando-tatsuya",
    nameJa: "安藤 達也",
    nameEn: "Tatsuya Ando",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 16,
    losses: 5,
    draws: 1,
    ko: 7,
    sub: 6,
    decision: 3,
    history: [],
    nickname: "遅れてきた\"怪物\"",
  },
  {
    slug: "sakuraba-taisei",
    nameJa: "桜庭 大世",
    nameEn: "Taisei Sakuraba",
    org: "rizin",
    weightClass: "ライト級",
    wins: 2,
    losses: 2,
    draws: 0,
    ko: 1,
    sub: 1,
    decision: 0,
    history: [],
    nickname: "Saku Jr.",
  },
  {
    slug: "usami-sho-patrick",
    nameJa: "宇佐美正パトリック",
    nameEn: "Patrick Usami",
    org: "rizin",
    weightClass: "ライト級",
    wins: 9,
    losses: 5,
    draws: 0,
    ko: 7,
    sub: 0,
    decision: 2,
    history: [],
    nickname: "聖なる破壊者",
  },
  {
    slug: "umeno-genji",
    nameJa: "梅野 源治",
    nameEn: "Genji Umeno",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 2,
    losses: 0,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 2,
    history: [],
    wikiTitleEn: "Genji Umeno",
    nickname: "日本ムエタイ界の至宝",
  },
  {
    slug: "kintaro",
    nameJa: "金太郎",
    nameEn: "Kintaro",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 16,
    losses: 15,
    draws: 2,
    ko: 9,
    sub: 3,
    decision: 4,
    history: [],
    nickname: "マサカリ殺法",
    wikiTitleJa: "金太郎 (格闘家)",
  },
  {
    slug: "suda-moeri",
    nameJa: "須田 萌里",
    nameEn: "Moeri Suda",
    org: "rizin",
    weightClass: "女子アトム級",
    wins: 15,
    losses: 7,
    draws: 0,
    ko: 0,
    sub: 10,
    decision: 5,
    history: [],
    wikiTitleEn: "Moeri Suda",
    nickname: "寝技の萌ちゃん",
  },
  {
    slug: "kubo-yuta",
    nameJa: "久保 優太",
    nameEn: "Yuta Kubo",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 5,
    losses: 3,
    draws: 0,
    ko: 2,
    sub: 1,
    decision: 2,
    history: [],
    wikiTitleEn: "Yuta Kubo",
    nickname: "微笑みスナイパー",
  },
  {
    slug: "takeda-koji",
    nameJa: "武田 光司",
    nameEn: "Koji Takeda",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 19,
    losses: 8,
    draws: 0,
    ko: 2,
    sub: 6,
    decision: 11,
    history: [],
    nickname: "漆黒のヘラクレス",
  },
  {
    slug: "tokoro-hideo",
    nameJa: "所 英男",
    nameEn: "Hideo Tokoro",
    org: "rizin",
    weightClass: "フライ級",
    wins: 36,
    losses: 34,
    draws: 1,
    ko: 6,
    sub: 21,
    decision: 9,
    history: [],
    wikiTitleJa: "所英男",
    nickname: "闘うフリーター",
  },
  {
    slug: "edpolo-king",
    nameJa: "エドポロキング",
    nameEn: "Edpolo King",
    org: "rizin",
    weightClass: "ヘビー級",
    wins: 3,
    losses: 0,
    draws: 0,
    ko: 3,
    sub: 0,
    decision: 0,
    history: [
      { date: "2025-03-30", opponent: "酒井リョウ", result: "win", method: "TKO（パウンド）", event: "RIZIN.50", round: "R2 2:32" },
      { date: "2024-12-31", opponent: "貴賢神", result: "win", method: "TKO（スタンドパンチ連打）", event: "RIZIN.49", round: "R1 3:22" },
      { date: "2024-05-26", opponent: "テリー・ワカンダ", result: "win", method: "TKO（パウンド）", event: "Rumble#3", round: "R1 0:15" },
    ],
    nickname: "アンダーグラウンド・ホームランキング",
  },
  {
    slug: "ueda-mikio",
    nameJa: "上田 幹雄",
    nameEn: "Mikio Ueda",
    org: "rizin",
    weightClass: "ヘビー級",
    wins: 5,
    losses: 3,
    draws: 0,
    ko: 5,
    sub: 0,
    decision: 0,
    history: [
      { date: "2025-07-27", opponent: "シビサイ頌真", result: "loss", method: "TKO", event: "超RIZIN.4 真夏の喧嘩祭り", round: "R1" },
      { date: "2025-05-04", opponent: "シビサイ頌真", result: "win", method: "KO（スタンドキック）", event: "RIZIN男祭り", round: "R1 1:03" },
      { date: "2024-12-31", opponent: "キム・テイン", result: "win", method: "KO", event: "RIZIN.49", round: "R1" },
      { date: "2024-06-09", opponent: "シェミスラブ・コバルチェク", result: "loss", method: "submission", event: "RIZIN.47", round: "R1" },
      { date: "2023-12-31", opponent: "スダリオ剛", result: "win", method: "TKO", event: "RIZIN.45", round: "R1" },
      { date: "2023-06-24", opponent: "関根秀樹", result: "win", method: "TKO", event: "RIZIN.43", round: "R1" },
      { date: "2022-12-04", opponent: "ソン・ムジェ", result: "win", method: "KO", event: "GRACHAN 58", round: "R1" },
      { date: "2022-04-17", opponent: "高阪剛", result: "loss", method: "TKO", event: "RIZIN.35", round: "R1" },
    ],
    nickname: "極真空手世界王者",
  },
  {
    slug: "sudario-go",
    nameJa: "スダリオ 剛",
    nameEn: "Go Sudario",
    org: "rizin",
    weightClass: "ヘビー級",
    wins: 9,
    losses: 4,
    draws: 0,
    ko: 8,
    sub: 0,
    decision: 1,
    history: [
      { date: "2025-05-04", opponent: "ジョゼ・アウグスト", result: "loss", method: "判定（0-3）", event: "RIZIN男祭り", round: "R3" },
      { date: "2024-11-17", opponent: "加藤久輝", result: "win", method: "TKO", event: "RIZIN LANDMARK 10", round: "R1" },
      { date: "2023-12-31", opponent: "上田幹雄", result: "loss", method: "TKO", event: "RIZIN.45", round: "R1" },
      { date: "2023-10-01", opponent: "イム・ドンファン", result: "win", method: "TKO", event: "RIZIN LANDMARK 6", round: "R1" },
      { date: "2023-04-29", opponent: "ロッキー・マルティネス", result: "win", method: "判定", event: "RIZIN LANDMARK 5", round: "R3" },
      { date: "2022-12-31", opponent: "ジュニア・タファ", result: "loss", method: "TKO", event: "RIZIN.40", round: "R1" },
      { date: "2022-10-23", opponent: "ヤノス・チューカス", result: "win", method: "TKO", event: "RIZIN.39", round: "R1" },
      { date: "2022-07-31", opponent: "関根秀樹", result: "win", method: "TKO", event: "RIZIN.37", round: "R1" },
      { date: "2021-10-24", opponent: "SAINT", result: "win", method: "KO", event: "RIZIN.31", round: "R1" },
      { date: "2021-06-13", opponent: "シビサイ頌真", result: "loss", method: "submission", event: "RIZIN.28", round: "R1" },
      { date: "2021-03-21", opponent: "宮本和志", result: "win", method: "KO", event: "RIZIN.27", round: "R1" },
      { date: "2020-12-31", opponent: "ミノワマン", result: "win", method: "TKO", event: "RIZIN.26", round: "R1" },
      { date: "2020-09-27", opponent: "ディラン・ジェイムス", result: "win", method: "TKO", event: "RIZIN.24", round: "R1" },
    ],
    nickname: "元 貴ノ富士",
  },
  {
    slug: "kikanoshin",
    nameJa: "貴賢神",
    nameEn: "Kikanoshin",
    org: "rizin",
    weightClass: "ヘビー級",
    wins: 4,
    losses: 4,
    draws: 0,
    ko: 4,
    sub: 0,
    decision: 0,
    history: [
      { date: "2026-06-06", opponent: "酒井リョウ", result: "win", method: "TKO（右ストレート→パウンド）", event: "RIZIN LANDMARK 14", round: "R1 1:16" },
      { date: "2025-11-03", opponent: "MAX吉田", result: "win", method: "TKO（グラウンドでの肘打ち）", event: "RIZIN LANDMARK 12", round: "R1 1:10" },
      { date: "2025-07-27", opponent: "稲田将", result: "win", method: "TKO（グラウンドでの肘打ち）", event: "超RIZIN.4 真夏の喧嘩祭り", round: "R2 2:28" },
      { date: "2024-12-31", opponent: "エドポロキング", result: "loss", method: "TKO（スタンドパンチ連打）", event: "RIZIN.49", round: "R1 3:22" },
      { date: "2024-03-23", opponent: "コーディー・ジェラベック", result: "win", method: "TKO（スタンドパンチ連打）", event: "RIZIN LANDMARK 9", round: "R1 2:58" },
      { date: "2023-10-01", opponent: "荒東英貴", result: "loss", method: "TKO（スタンドパンチ連打）", event: "RIZIN LANDMARK 6", round: "R2 4:49" },
      { date: "2022-11-06", opponent: "カルリ・ギブレイン", result: "loss", method: "TKO（グラウンドパンチ）", event: "RIZIN LANDMARK 4", round: "R1 4:35" },
      { date: "2022-04-16", opponent: "関根秀樹", result: "loss", method: "TKO（サッカーボールキック）", event: "RIZIN TRIGGER 3rd", round: "R2 3:49" },
    ],
    wikiTitleJa: "貴賢神",
    nickname: "バイオレンススモウレスラー",
  },
  {
    slug: "kouzi",
    nameJa: "皇治",
    nameEn: "Kouzi",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 1,
    losses: 1,
    draws: 0,
    ko: 0,
    sub: 0,
    decision: 0,
    history: [],
    wikiTitleJa: "皇治",
    nickname: "鋼のエンペラー",
  },
  {
    slug: "suzuki-hiroaki",
    nameJa: "鈴木 博昭",
    nameEn: "Hiroaki Suzuki",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 6,
    losses: 6,
    draws: 0,
    ko: 4,
    sub: 0,
    decision: 2,
    history: [
      { date: "2025-09-28", opponent: "ファン・イェーロウ", result: "win", method: "判定（2-1）", event: "RIZIN.51", round: "R3" },
      { date: "2025-06-14", opponent: "山本空良", result: "win", method: "判定（3-0）", event: "RIZIN LANDMARK 11", round: "R3" },
      { date: "2024-12-31", opponent: "安井飛馬", result: "loss", method: "判定（0-3）", event: "RIZIN DECADE", round: "R3" },
      { date: "2024-11-17", opponent: "秋元強真", result: "loss", method: "判定（0-3）", event: "RIZIN LANDMARK 10", round: "R3" },
      { date: "2024-07-28", opponent: "YA-MAN", result: "loss", method: "KO（左フック）", event: "超RIZIN.3", round: "R1 3:28" },
      { date: "2024-02-24", opponent: "芦田崇宏", result: "win", method: "TKO（グラウンドパンチ）", event: "RIZIN LANDMARK 8", round: "R1 4:29" },
      { date: "2023-06-24", opponent: "西谷大成", result: "win", method: "TKO（左フック→パウンド）", event: "RIZIN.43", round: "R1 0:56" },
      { date: "2022-11-06", opponent: "青井人", result: "loss", method: "判定（0-3）", event: "RIZIN LANDMARK 4", round: "R3" },
      { date: "2022-07-02", opponent: "平本蓮", result: "loss", method: "判定（1-2）", event: "RIZIN.36", round: "R3" },
      { date: "2022-03-06", opponent: "昇侍", result: "win", method: "KO（左フック）", event: "RIZIN LANDMARK vol.2", round: "R1 1:12" },
      { date: "2021-12-31", opponent: "萩原京平", result: "loss", method: "判定（0-3）", event: "RIZIN.33", round: "R3" },
      { date: "2021-10-02", opponent: "奥田啓介", result: "win", method: "TKO（左膝蹴り→パウンド）", event: "RIZIN LANDMARK vol.1", round: "R1 1:42" },
    ],
    wikiTitleJa: "鈴木博昭 (格闘家)",
    nickname: "怪物くん",
  },
  {
    slug: "miyagawa-hinata",
    nameJa: "宮川 日向",
    nameEn: "Hinata Miyagawa",
    org: "rizin",
    weightClass: "バンタム級",
    wins: 7,
    losses: 6,
    draws: 0,
    ko: 4,
    sub: 0,
    decision: 3,
    history: [
      { date: "2026-04-12", opponent: "井上聖矢", result: "win", method: "判定（0-3）", event: "RIZIN LANDMARK 13", round: "R3" },
      { date: "2025-11-03", opponent: "MG眞介", result: "win", method: "TKO（グラウンドパンチ）", event: "RIZIN LANDMARK 12", round: "R1 1:52" },
      { date: "2025-06-08", opponent: "ルキヤ", result: "loss", method: "TKO（右フック→パウンド）", event: "GLADIATOR 031", round: "R2 0:54" },
      { date: "2025-04-06", opponent: "永留惇平", result: "loss", method: "判定（0-3）", event: "GLADIATOR 030", round: "R2" },
      { date: "2025-01-12", opponent: "三浦颯太", result: "win", method: "判定（3-0）", event: "GLADIATOR 029", round: "R2" },
      { date: "2024-10-06", opponent: "今井健斗", result: "loss", method: "判定（0-3）", event: "GLADIATOR 028", round: "R2" },
      { date: "2024-06-02", opponent: "久保田洸平", result: "win", method: "TKO（パウンド）", event: "DEEP OSAKA IMPACT 2024", round: "R2 2:28" },
      { date: "2024-03-03", opponent: "八木祐輔", result: "win", method: "TKO（パウンド）", event: "GLADIATOR 025", round: "R1 3:39" },
      { date: "2023-12-09", opponent: "古賀珠楠", result: "win", method: "TKO（右ストレート→パウンド）", event: "GLADIATOR 024", round: "R2 4:53" },
      { date: "2023-01-22", opponent: "中西テツオ", result: "loss", method: "submission (rear-naked choke)", event: "GLADIATOR 021", round: "R1 2:43" },
      { date: "2022-06-26", opponent: "秋元強真", result: "loss", method: "判定（0-3）", event: "GLADIATOR 018", round: "R2" },
      { date: "2021-11-21", opponent: "井上暉也", result: "loss", method: "判定（1-2）", event: "DEEP OSAKA IMPACT 2021", round: "R2" },
      { date: "2025-09-14", opponent: "上田直毅", result: "win", method: "判定（3-0）", event: "TTF CHALLENGE 11", round: "延長R" },
    ],
    nickname: "スモーカーの若獅子",
  },
  {
    slug: "naoki",
    nameJa: "直樹",
    nameEn: "Naoki",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 3,
    losses: 2,
    draws: 0,
    ko: 2,
    sub: 1,
    decision: 0,
    history: [
      { date: "2026-06-06", opponent: "黒井海成", result: "win", method: "TKO（左膝蹴り→パウンド）", event: "RIZIN LANDMARK 14", round: "R1 3:37" },
      { date: "2026-03-20", opponent: "木下カラテ", result: "win", method: "submission (rear-naked choke)", event: "DEEP 130 IMPACT", round: "R1 0:22" },
      { date: "2025-11-02", opponent: "三井俊希", result: "loss", method: "KO", event: "DEEP 128 IMPACT", round: "R1 0:27" },
      { date: "2025-07-27", opponent: "芦田崇宏", result: "loss", method: "判定（0-3）", event: "超RIZIN.4 真夏の喧嘩祭り", round: "R3" },
      { date: "2025-05-05", opponent: "奥山貴大", result: "win", method: "KO", event: "DEEP 125 IMPACT", round: "R1 1:48" },
    ],
    nickname: "倒し屋ジョーカー",
  },
  {
    slug: "mizuno-shinta",
    nameJa: "水野 新太",
    nameEn: "Shinta Mizuno",
    org: "rizin",
    weightClass: "フェザー級",
    wins: 9,
    losses: 1,
    draws: 0,
    ko: 2,
    sub: 1,
    decision: 6,
    history: [
      { date: "2026-05-04", opponent: "牛久絢太郎", result: "win", method: "判定（5-0）", event: "DEEP 131 IMPACT", round: "R3" },
      { date: "2025-12-14", opponent: "青井人", result: "loss", method: "判定（1-4）", event: "DEEP 129 IMPACT", round: "R3" },
      { date: "2025-08-17", opponent: "高橋遼伍", result: "win", method: "判定（5-0）", event: "DEEP 126 IMPACT", round: "R3" },
      { date: "2025-05-05", opponent: "海飛", result: "win", method: "判定（0-5）", event: "DEEP 125 IMPACT", round: "R3" },
      { date: "2025-03-15", opponent: "芦田崇宏", result: "win", method: "TKO", event: "DEEP 124 IMPACT", round: "R1 4:20" },
      { date: "2024-11-04", opponent: "太田将吾", result: "win", method: "判定（3-0）", event: "DEEP 122 IMPACT", round: "R2" },
      { date: "2024-09-08", opponent: "石塚一", result: "win", method: "TKO", event: "DEEP TOKYO IMPACT 2024", round: "R2 0:56" },
      { date: "2024-02-18", opponent: "Lil", result: "win", method: "判定（3-0）", event: "Fighting NEXUS vol.34", round: "R2" },
      { date: "2023-12-10", opponent: "横山辰也", result: "win", method: "判定（3-0）", event: "Fighting NEXUS vol.33", round: "R2" },
      { date: "2023-10-15", opponent: "清水博人", result: "win", method: "submission (rear-naked choke)", event: "Fighting NEXUS BAYSIDE BATTLE", round: "R1 4:01" },
    ],
    noNickname: true,
  },
];

export function getFighter(slug: string): Fighter | undefined {
  return FIGHTERS.find((f) => f.slug === slug);
}

export interface FighterRates {
  winRate: number | null; // 勝率（%） wins / (wins+losses)。引き分けは母数に含めない
  finishRate: number | null; // フィニッシュ率（%） (KO+一本) / wins
}

export function calcFighterRates(f: Pick<Fighter, "wins" | "losses" | "draws" | "ko" | "sub">): FighterRates {
  // 勝率は勝敗のみで算出（引き分けは母数から除外）
  const decided = f.wins + f.losses;
  const winRate = decided > 0 ? Math.round((f.wins / decided) * 100) : null;
  const finishRate = f.wins > 0 ? Math.round(((f.ko + f.sub) / f.wins) * 100) : null;
  return { winRate, finishRate };
}

// 任意の文字列（対戦カード上の選手名など）からMニュース掲載選手を探す。
// 大会結果ページ・選手の試合履歴テーブル双方の内部リンク生成で使う共通ロジック。
export function findFighterSlugByName(name: string, excludeSlug?: string): string | null {
  // スペース・全角スペースを除いて正規化して照合する
  const norm = (s: string) => s.replace(/[\s　]/g, "");
  const normName = norm(name);
  const match = FIGHTERS.find((f) => {
    if (f.slug === excludeSlug) return false;
    if (norm(f.nameJa) === normName) return true;
    if (f.nameEn === name) return true;
    // 英名を正規化して一致確認（大文字小文字を無視）
    if (f.nameEn.toLowerCase() === name.toLowerCase()) return true;
    return false;
  });
  return match ? match.slug : null;
}
